- alias: Trigger alarm waterleak
  trigger:
    - platform: state
      entity_id: 
        binary_sensor.kitchen_waterleak,
        binary_sensor.wc_waterleak,
        binary_sensor.bathroom_waterleak
      to: "on"
  action:
    - service: script.alarm_alert
      data_template:
        message: "Утечка воды {{ trigger.entity_id }}"
