- alias: Trigger alarm armed away
  trigger:
    - platform: state
      entity_id: 
        binary_sensor.livingroom_motion, 
        binary_sensor.livingroom_window,
        binary_sensor.livingroom_balcony,
        binary_sensor.bedroom_motion,
        binary_sensor.bedroom_window,
        binary_sensor.kitchen_motion,
        binary_sensor.kitchen_window,
        binary_sensor.hall_motion,
        binary_sensor.hall_entrance
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: script.alarm_alert_view
      data_template:
        message: "Нарушение периметра. Сработал {{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].name }} в {{ trigger.entity_id.split('.')[1].split('_')[0] }}"

- alias: Trigger alarm waterleak
  trigger:
    - platform: state
      entity_id: 
        binary_sensor.kitchen_waterleak,
        binary_sensor.wc_waterleak,
        binary_sensor.bathroom_waterleak
      to: "on"
  action:
    - service: script.alarm_alert
      data_template:
        message: "Утечка воды {{ trigger.entity_id }}"
