- alias: Trigger alarm armed away
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion,
                 binary_sensor.livingroom_window, 
                 binary_sensor.livingroom_balcony,
                 binary_sensor.hall_motion,
                 binary_sensor.hall_entrance,
                 binary_sensor.kitchen_window,
                 binary_sensor.bedroom_window,
                 binary_sensor.bedroom_motion
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.telegram
      data_template:
        message: >-
          Нарушение периметра.
          {%- for state in states.sensor if state.entity_id == trigger.entity_id -%}
            {{ state.attributes.friendly_name }} сработал.
          {%- endfor -%}