- alias: Message when armed
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: disarmed
  action:
    - service: notify.telegram
      data_template:
        message: Система снята с охраны

- alias: Message when disarmed
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: armed_away
  action:
    - service: notify.telegram
      data_template:
        message: Система под охраной
