- alias: Turn on corridor light when disarmed
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: disarmed
  condition:
    - condition: time
      after: "17:00:00"
      before: "07:00:00"
  action:
    - service: homeassistant.turn_on
      entity_id: light.corridor

- alias: Turn off all when armed
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: armed_away
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_off
      entity_id: group.all_fans

- alias: Turn on corridor light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: "on"
  condition:
    - condition: time
      after: "23:00:00"
      before: "06:00:00"
  action:
    service: homeassistant.turn_on
    entity_id: light.corridor

- alias: Turn off corridor light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: "off"
    for:
      minutes: 5
  condition:
    - condition: time
      after: "23:00:00"
      before: "06:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: light.corridor