# - alias: Turn on corridor light when disarmed
#   trigger:
#     platform: state
#     entity_id: alarm_control_panel.ha_alarm
#     to: disarmed
#   condition:
#     - condition: time
#       after: "17:00:00"
#       before: "07:00:00"
#   action:
#     - service: homeassistant.turn_on
#       entity_id: light.corridor

# - alias: Turn off all when armed
#   trigger:
#     platform: state
#     entity_id: alarm_control_panel.ha_alarm
#     to: armed_away
#   action:
#     - service: homeassistant.turn_off
#       entity_id: group.all_lights
#     - service: homeassistant.turn_off
#       entity_id: group.all_fans

- alias: Turn on corridor light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: "on"
  condition:
    - condition: time
      after: "21:00:00"
      before: "06:00:00"
    - condition: state
      entity_id: input_boolean.automation_light
      state: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_back
        brightness: 50
        rgb_color: [255,255,255]
- alias: Turn off corridor light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: "off"
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.automation_light
      state: "on"
    - condition: time
      after: "21:00:00"
      before: "06:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.hall_back
