- alias: Oksana Came Home
  trigger:
   platform: state
   entity_id: device_tracker.phone_oksana
   to: home
  condition:
    condition: state
    entity_id: device_tracker.google_maps_104258330239786803059
    state: home
  action:
    service: notify.telegram
    data_template:
      message: "Оксана вернулась домой"

- alias: Andrew Came Home
  trigger:
    platform: state
    entity_id: device_tracker.phone_drronnie
    to: home
  condition:
    condition: state
    entity_id: device_tracker.google_maps_105861814760109955404
    state: home
  action:
    service: notify.telegram
    data_template:
      message: "Андрей вернулся домой"

- alias: Oksana Left Home
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.google_maps_104258330239786803059
  action:
    service: notify.telegram
    data_template:
      message: "Оксана ушла из дома"

- alias: Andrew Left Home
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.google_maps_105861814760109955404
  action:
    service: notify.telegram
    data_template:
      message: "Андрей ушел из дома"

- alias: Oksana is Near Home
  trigger:
    platform: state
    entity_id: device_tracker.google_maps_104258330239786803059
    to: home
    for:
      minutes: 1
  action:
    service: notify.telegram
    data_template:
      message: "Оксана где-то рядом с домом"

- alias: Andrew is Near Home
  trigger:
    platform: state
    entity_id: device_tracker.google_maps_105861814760109955404
    to: home
    for:
      minutes: 1
  action:
    service: notify.telegram
    data_template:
      message: "Андрей где-то рядом с домом"

- alias: Oksana Came Motherinlaw
  trigger:
    platform: zone
    event: enter
    zone: zone.motherinlaw
    entity_id: device_tracker.google_maps_104258330239786803059
  action:
    service: notify.telegram
    data_template:
      message: "Оксана у тёщи"

- alias: Andrew Came Work
  trigger:
    platform: zone
    event: enter
    zone: zone.work
    entity_id: device_tracker.google_maps_105861814760109955404
  action:
    service: notify.telegram
    data_template:
      message: "Андрей на работе"

- alias: Andrew Left Work
  trigger:
    platform: zone
    event: leave
    zone: zone.work
    entity_id: device_tracker.google_maps_105861814760109955404
  action:
    service: notify.telegram
    data_template:
      message: "Андрей ушел с работы"