- alias: Somebody Came Motherinlaw
  trigger:
    platform: state
    entity_id:
      device_tracker.google_maps_104258330239786803059,
      device_tracker.google_maps_105861814760109955404
    from: not_home
    to: motherinlaw
    for:
      minutes: 5
  action:
    service: notify.telegram
    data_template:
      message: "{{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].name }} у тёщи."

- alias: Andrew Came Work
  trigger:
    platform: state
    entity_id:
      device_tracker.google_maps_105861814760109955404
    from: not_home
    to: work
    for:
      minutes: 5
  action:
    service: notify.telegram
    data_template:
      message: "Андрей на работе"

- alias: Andrew Left Work
  trigger:
    platform: state
    entity_id:
      device_tracker.google_maps_105861814760109955404
    from: work
    to: not_home
    for:
      minutes: 5
  action:
    service: notify.telegram
    data_template:
      message: "Андрей ушел с работы"

- alias: Somebody Left Home
  trigger:
    platform: state
    entity_id:
      device_tracker.google_maps_104258330239786803059,
      device_tracker.google_maps_105861814760109955404
    from: home
    to: not_home
    for:
      minutes: 5
  action:
    service: notify.telegram
    data_template:
      message: "{{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].name }} не дома."

- alias: Somebody Near Home
  trigger:
    platform: state
    entity_id:
      device_tracker.google_maps_104258330239786803059,
      device_tracker.google_maps_105861814760109955404
    to: home
    for:
      minutes: 5
  action:
    service: notify.telegram
    data_template:
      message: "{{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].name }} возле дома."