- alias: Somebody Came Motherinlaw
  trigger:
    platform: zone
    entity_id:
      device_tracker.google_maps_104258330239786803059,
      device_tracker.google_maps_105861814760109955404
    zone: zone.motherinlaw
    event: enter
  action:
    service: notify.telegram
    data_template:
      message: "{{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].name }} у тёщи."

- alias: Andrew Came Work
  trigger:
    platform: zone
    entity_id:
      device_tracker.google_maps_105861814760109955404
    zone: zone.work
    event: enter
  action:
    service: notify.telegram
    data_template:
      message: "Андрей на работе"

- alias: Andrew Left Work
  trigger:
    platform: zone
    entity_id:
      device_tracker.google_maps_105861814760109955404
    zone: zone.work
    event: leave
  action:
    service: notify.telegram
    data_template:
      message: "Андрей ушел с работы"

- alias: Somebody Near Home
  trigger:
    platform: zone
    entity_id:
      device_tracker.google_maps_104258330239786803059,
      device_tracker.google_maps_105861814760109955404
    zone: zone.home
    event: enter
  action:
    service: notify.telegram
    data_template:
      message: "{{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].name }} возле дома."

- alias: Somebody Left Home
  trigger:
    platform: zone
    entity_id:
      device_tracker.google_maps_104258330239786803059,
      device_tracker.google_maps_105861814760109955404
    zone: zone.home
    event: leave
  action:
    service: notify.telegram
    data_template:
      message: "{{ states[trigger.entity_id.split('.')[0]][trigger.entity_id.split('.')[1]].name }} не дома."