- alias: mqtt_sensor_redirect
  trigger:
    - platform: mqtt
      topic: bridge/rfin
  action:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfin_sensor
        payload_template: "{{trigger.payload[9:]}}"

# security alarm
- alias: Security ARM_AWAY
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005444C0"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA8"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005D7DC0"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: ARM_AWAY
- alias: Security ARM_HOME
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "800544403"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA1"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005D7D03"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: ARM_HOME
- alias: Security DISARM
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "80054440C"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA4"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005D7D0C"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: DISARM
# - alias: Security PANIC
#   trigger:
#     - platform: mqtt
#       topic: bridge/rfin_sensor
#       payload: "800544430"
#   trigger:
#     - platform: mqtt
#       topic: bridge/rfin_sensor
#       payload: "8000CFBA2"
#     - platform: mqtt
#       topic: bridge/rfin_sensor
#       payload: "8005D7D30"
#   action:
#     - service: mqtt.publish
#       data_template:
#         topic: home/alarm
#         payload_template: triggered

- alias: Trigger alarm armed away
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.livingroom_window
      to: "on"
    - platform: state
      entity_id: binary_sensor.livingroom_balcony
      to: "on"
    - platform: state
      entity_id: binary_sensor.hall_motion
      to: "on"
    - platform: state
      entity_id: binary_sensor.hall_entrance
      to: "on"
    - platform: state
      entity_id: binary_sensor.kitchen_window
      to: "on"
    - platform: state
      entity_id: binary_sensor.bedroom_window
      to: "on"
    - platform: state
      entity_id: binary_sensor.bedroom_motion
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.telegram
      data_template:
        message: Нарушение периметра

# Lights automation
- alias: Turn on corridor light when disarmed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
  condition:
    - condition: time
      after: "17:00:00"
      before: "07:00:00"
  action:
    - service: homeassistant.turn_on
      entity_id: light.corridor
- alias: Turn on corridor light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: "on"
  condition:
    - condition: time
      after: "23:00:00"
      before: "06:00:00"
  action:
    service: homeassistant.turn_on
    entity_id: light.corridor
- alias: Turn off corridor light 10 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion
    to: "off"
    for:
      minutes: 10
  condition:
    - condition: time
      after: "23:00:00"
      before: "06:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: light.corridor

# Geolocation triggers
- alias: Someone Came Home
   trigger:
     platform: zone
     event: enter
     zone: zone.home
     entity_id: device_tracker.google_maps_105861814760109955404
   action:
     service: notify.telegram
     data_template:
       message: "{{ trigger.to_state.attributes.friendly_name }} дома"
- alias: Someone Left Home
   trigger:
     platform: zone
     event: leave
     zone: zone.home
     entity_id: device_tracker.google_maps_105861814760109955404
   action:
     service: notify.telegram
     data_template:
       message: "{{ trigger.to_state.attributes.friendly_name }} ушел из дома"
- alias: Someone Came Work
   trigger:
     platform: zone
     event: enter
     zone: zone.work
     entity_id: device_tracker.google_maps_105861814760109955404
   action:
     service: notify.telegram
     data_template:
       message: "{{ trigger.to_state.attributes.friendly_name }} на работе"
- alias: Someone Left Work
   trigger:
     platform: zone
     event: leave
     zone: zone.work
     entity_id: device_tracker.google_maps_105861814760109955404
   action:
     service: notify.telegram
     data_template:
       message: "{{ trigger.to_state.attributes.friendly_name }} ушел с работы"
- alias: Someone Came Motherinlaw
   trigger:
     platform: zone
     event: enter
     zone: zone.motherinlaw
     entity_id: device_tracker.google_maps_105861814760109955404
   action:
     service: notify.telegram
     data_template:
       message: "{{ trigger.to_state.attributes.friendly_name }} у тёщи"


# weather notification
- alias: Начался дождь
  trigger:
    - platform: state
      entity_id: sensor.precip_intensity
      to: "rain"
  action:
    service: notify.telegram
    data_template:
      message: "Начался дождь"
- alias: Закончился дождь 
  trigger:
    - platform: state
      entity_id: sensor.precip_intensity
      to: "None"
  action:
    service: notify.telegram
    data_template:
      message: "Закончился дождь"
