- id: mqtt_sensor_redirect
  alias: Pulsante Marty ramen
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_9"
  action:
    - service: mqtt.publish
      data_template:     
        payload_template: '{{trigger.payload[9:]}}'
- id: oksana_come
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: 'not_home'
     to: 'home'
  action:
    service: notify.telegram
    data_template:
      message: Оксана вернулась домой
- id: oksana_left
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: 'home'
     to: 'not_home'
  action:
    service: notify.telegram
    data_template:
      message: Оксана вышла из дома
