- id: oksana come home notify
  alias: 'Оксана пришла домой'
  initial_state: 'on'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: 'not_home'
     to: 'home'
  action:
    service: notify.telegram
    data_template:
      message: Оксана вернулась домой
- id: oksana left home notify
  alias: 'Оксана вышла из домой'
  initial_state: 'on'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: 'home'
     to: 'not_home'
  action:
    service: notify.telegram
    data_template:
      message: Оксана вышла из дома
