- id: mqtt_sensor_redirect
  trigger:
    - platform: mqtt
      topic: "bridge/rfin"
  action:
    - service: mqtt.publish
      data_template:
        topic: "bridge/rfin_sensor"
        payload_template: '{{trigger.payload[9:]}}'

- id: security_panel
  trigger:
    - platform: mqtt
      topic: "security/status/set"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: '{{trigger.payload}}'

# drronnie's rc
- id: security_armed_away_drronnie
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_sensor"
      payload: "8005444C0"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: "armed_away"
- id: security_armed_home_drronnie
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_sensor"
      payload: "800544403"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: "armed_home"
- id: security_disarmed_drronnie
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_sensor"
      payload: "80054440C"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: "disarmed"
- id: security_triggered_drronnie
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_sensor"
      payload: "800544430"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: "triggered"
# oksana's rc
- id: security_armed_away_oksana
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_sensor"
      payload: "8005D7DC0"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: "armed_away"
- id: security_armed_home_oksana
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_sensor"
      payload: "8005D7D03"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: "armed_home"
- id: security_disarmed_oksana
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_sensor"
      payload: "8005D7D30"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: "disarmed"
- id: security_triggered_oksana
  trigger:
    - platform: mqtt
      topic: "bridge/rfin_sensor"
      payload: "800544430"
  action:
    - service: mqtt.publish
      data_template:
        topic: "security/status"
        payload_template: "triggered"

- id: oksana_come
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: 'not_home'
     to: 'home'
  action:
    service: notify.telegram
    data_template:
      message: Оксана вернулась домой
- id: oksana_left
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: 'home'
     to: 'not_home'
  action:
    service: notify.telegram
    data_template:
      message: Оксана вышла из дома
