- alias: mqtt_sensor_redirect
  trigger:
    - platform: mqtt
      topic: bridge/rfin
  action:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfin_sensor
        payload_template: "{{trigger.payload[9:]}}"

# drronnie rc
- alias: security_armed_away_drronnie
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005444C0"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: ARM_AWAY
- alias: security_armed_home_drronnie
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "800544403"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: ARM_HOME
- alias: security_disarmed_drronnie
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "80054440C"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: DISARM
# - alias: security_triggered_drronnie
#   trigger:
#     - platform: mqtt
#       topic: bridge/rfin_sensor
#       payload: "800544430"
#   action:
#     - service: mqtt.publish
#       data_template:
#         topic: home/alarm
#         payload_template: triggered
# oksana rc
- alias: security_armed_away_oksana
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA8"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: ARM_AWAY
- alias: security_armed_home_oksana
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA1"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: ARM_HOME
- alias: security_disarmed_oksana
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA4"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: DISARM
# - alias: security_triggered_oksana
#   trigger:
#     - platform: mqtt
#       topic: bridge/rfin_sensor
#       payload: "8000CFBA2"
#   action:
#     - service: mqtt.publish
#       data_template:
#         topic: home/alarm/set
#         payload: triggered

- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.livingroom_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.livingroom_balcony
      to: 'on'
    - platform: state
      entity_id: binary_sensor.hall_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.hall_entrance
      to: 'on'
    - platform: state
      entity_id: binary_sensor.kitchen_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_window
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.telegram
      data_template:
        message: Нарушение периметра

- alias: oksana_come
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: not_home
     to: home
  action:
    service: notify.telegram
    data_template:
      message: Оксана вернулась домой
- alias: oksana_left
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: home
     to: not_home
  action:
    service: notify.telegram
    data_template:
      message: Оксана вышла из дома