- id: oksana come home notify
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: 'not_home'
     to: 'home'
  action:
    service: notify.telegram
    data_template:
      message: Оксана вернулась домой
- id: oksana left home notify
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     from: 'home'
     to: 'not_home'
  action:
    service: notify.telegram
    data_template:
      message: Оксана вышла из дома
- id: andrew come home notify
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_andrew
     from: 'not_home'
     to: 'home'
  action:
    service: notify.telegram
    data_template:
      message: Андрей вернулся домой
- id: andrew left home notify
  initial_state: 'off'
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_andrew
     from: 'home'
     to: 'not_home'
  action:
    service: notify.telegram
    data_template:
      message: Андрей вышел из дома
  