homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Kiev
  # Customization file
  customize: !include customize.yaml

lovelace:
  mode: yaml
  
# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

zigbee:
  device: /dev/ttyACM0
  baud: 115200
  
http:
  base_url: nas.drronniesoft.info:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

zone:
  name: Дом
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 50
  icon: mdi:home

zone 2:
  name: Работа
  latitude: !secret latitude_work
  longitude: !secret longitude_work
  radius: 50
  icon: mdi:office-building

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

mqtt:
  broker: 192.168.1.4
  port: 1883

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

telegram_bot:
  platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chatid_andrey
    - !secret telegram_chatid_oksana

notify:
  - name: telegram
    platform: telegram
    api_key: !secret telegram_key
    chat_id: !secret telegram_chatid_andrey
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key
    

group: !include groups.yaml
automation: !include automation.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
light: !include light.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
climate: !include climate.yaml