homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret lon_home
  elevation: 0
  unit_system: metric
  time_zone: Europe/Kiev
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.20
        - 192.168.1.21
        - 192.168.1.23
    - type: legacy_api_password
      api_password: !secret http_password
  packages: !include_dir_named _packages/

# sia:
#   port: 1234
#   hubs:
#     - name: ajax
#       account: 7F192

lovelace:
  mode: yaml
  
frontend:
config:
http:
  base_url: nas.drronniesoft.info:8123
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

discovery:
conversation:
dialogflow:
history:
logbook:
map:
sun:

#logger:
#  default: debug

recorder:
  purge_keep_days: 365
  db_url: !secret mssql

hassio:

smartir:

upnp:
  port_mapping: true
  ports:
    hass: 8123

zone:
  - name: home
    latitude: !secret lat_home
    longitude: !secret lon_home
    radius: 100
    icon: mdi:account-multiple
  - name: work
    latitude: !secret lat_work
    longitude: !secret lon_work
    radius: 100
    icon: mdi:office-building
  - name: motherinlaw
    latitude: !secret lat_motherinlaw
    longitude: !secret lon_motherinlaw
    radius: 100
    icon: mdi:human-female

weather:
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily

mqtt:
  password: hello
  discovery: true
  discovery_prefix: homeassistant

#tts:
#  - platform: google

#cloud:
system_health:

api:

telegram_bot:
  platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chatid_andrey
    - !secret telegram_chatid_oksana
    - !secret telegram_chatid_group

notify:
  - name: telegram
    platform: telegram
    api_key: !secret telegram_key
    chat_id: !secret telegram_chatid_group
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

automation: !include_dir_merge_list _automation/
script: !include_dir_merge_named _scripts/
sensor: !include sensor.yaml
switch: !include switch.yaml
input_select: !include input_select.yaml
camera: !include camera.yaml