title: Andrew and Oksana's home
resources:
  - type: module
    url: /local/custom_ui/weather-card.js?v=0.24
views:
  - id: info
    title: Информация
    icon: mdi:information
    badges:
      - device_tracker.router_main
      - device_tracker.router_kitchen
      - device_tracker.router_livingroom
      - device_tracker.media_mibox_livingroom
      - device_tracker.media_ghmini_bedroom
    cards:
      - type: entity-filter
        entities:
          - device_tracker.phone_oksana
          - device_tracker.phone_andrey
        state_filter:
          - home
        card: 
          type: glance
          title: Кто дома
      - type: glance
        title: Медиа
        entities:
          - device_tracker.router_main
          - device_tracker.router_kitchen
          - device_tracker.router_livingroom
          - device_tracker.media_mibox_livingroom
          - device_tracker.media_ghmini_bedroom
      - type: glance
        title: Камреы
        entities:
          - device_tracker.camera_loft
          - device_tracker.camera_entrance
          - device_tracker.camera_tambour
          - device_tracker.camera_livingroom
          - device_tracker.camera_bedroom
          - device_tracker.camera_cristoph
          - device_tracker.camera_kitchen
          - device_tracker.camera_hall
          - device_tracker.camera_mobile
      - type: glance
        title: IoT
        entities:
          - device_trackeriot_rmpro_livingroom
          - device_trackeriot_a1_bedroom
          - device_trackeriot_mp1_kitchen
          - device_trackeriot_bridge_hall
          - device_trackeriot_powb1_wc
          - device_trackeriot_mc1_bedroom
  - id: camera
    title: Камеры
    icon: mdi:camera
    cards:
      - type: picture-glance
        title: Зал
        entities:
          - light.livingroom
          - light.livingroom_back
        camera_image: camera.zal
      - type: picture-glance
        title: Спальня
        entities:
          - light.bedroom
          - light.bedroom_back
        camera_image: camera.spalnia
      - type: picture-glance
        title: Кухня
        entities:
          - light.kitchen
          - light.kitchen_back
        camera_image: camera.kukhnia
      - type: picture-glance
        title: Прихожая
        entities:
          - light.hall
        camera_image: camera.prikhozhaia
  - id: home
    title: Дом
    icon: 'mdi:home-assistant'
    cards:
      - type: entities
        title: Датчики
        entities:
          - type: state-icon
            entity: binary_sensor.livingroom_motion
          - type: state-icon
            entity: binary_sensor.livingroom_window          
          - type: state-icon
            entity: binary_sensor.livingroom_balcony
      - type: entities
        title: Освещение
        entities:
          - toggle: true
            entity: light.livingroom
          - toggle: true
            entity: light.livingroom_back
          - type: divider
          - toggle: true
            entity: light.bedroom
          - toggle: true
            entity: light.bedroom_back
          - type: divider
          - toggle: true
            entity: light.kitchen
          - toggle: true
            entity: light.kitchen_back
          - type: divider
          - toggle: true
            entity: light.wc
          - type: divider
          - toggle: true
            entity: light.corridor
          - type: divider
          - toggle: true
            entity: light.bathroom
          - type: divider
          - toggle: true
            entity: light.hall
  - id: weather
    title: Погода
    icon: 'mdi:weather-cloudy'
    cards:
      - entity: weather.dark_sky
        type: 'custom:weather-card'
      - type: entities
        entities:
          - type: section
            label: Спальня
          - sensor.br_bedroom_temperature
          - sensor.br_bedroom_humidity
          - type: section
            label: Зал
          - sensor.br_livingroom_temperature
        show_header_toggle: false
      - type: iframe
        url: >-
          https://embed.windy.com/embed2.html?lat=50.455&lon=30.524&zoom=10&overlay=wind&location=coordinates
        aspect_ratio: 90%
  - badges:
      - group.all_lights
      - group.all_switches
    title: test
    cards: []
