title: Дом Андрея и Оксаны
resources:
  - type: module
    url: /local/custom_ui/weather-card.js?v=0.24
views:
  - id: climate
    title: Климат
    icon: mdi:weather-cloudy
    cards:
      - type: vertical-stack
        cards:
          - entity: weather.dark_sky
            type: custom:weather-card
          - type: horizontal-stack
            cards:
            - type: glance
              title: Улица
              show_name: false
              entities:
                - sensor.dark_sky_temperature
                - sensor.dark_sky_humidity
                - sensor.dark_sky_pressure
            - type: glance
              title: Зал
              show_name: false
              entities:
                - sensor.br_livingroom_temperature
                - sensor.br_livingroom_humidity
          - type: horizontal-stack
            cards:
            - type: glance
              title: Спальня
              show_name: false
              entities:
                - sensor.br_bedroom_temperature
                - sensor.br_bedroom_humidity
            - type: glance
              title: Кухня
              show_name: false
              entities:
                - sensor.kitchen_temperature
                - sensor.kitchen_humidity
      - type: history-graph
        title: Температура
        entities:
          - entity: sensor.br_livingroom_temperature
            name: Зал
          - entity: sensor.br_bedroom_temperature
            name: Спальня
          - entity: sensor.kitchen_temperature
            name: Кухня
      - type: history-graph
        title: Влажность
        entities:
          - entity: sensor.br_livingroom_humidity
            name: Зал
          - entity: sensor.br_bedroom_humidity
            name: Спальня
          - entity: sensor.kitchen_humidity
            name: Кухня
      - type: iframe
        url: "https://embed.windy.com/embed2.html?lat=50.455&lon=30.524&zoom=10&overlay=wind&location=coordinates"
        aspect_ratio: 90%
  - id: security
    title: Информация
    icon: mdi:shield
    badges:
      - device_tracker.phone_oksana
      - device_tracker.phone_drronnie
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.ha_alarm
        name: Охрана
        states:
          - arm_away
          - arm_home
      - type: entities
        title: Датчики
        show_header_toggle: false
        entities:
          - type: section
            label: Зал
          - type: state-icon
            entity: binary_sensor.livingroom_motion
          - type: state-icon
            entity: binary_sensor.livingroom_window          
          - type: state-icon
            entity: binary_sensor.livingroom_balcony
          - type: section
            label: Прихожая
          - type: state-icon
            entity: binary_sensor.hall_motion
          - type: state-icon
            entity: binary_sensor.hall_entrance
          - type: section
            label: Кухня
          - type: state-icon
            entity: binary_sensor.kitchen_window          
          - type: section
            label: Спальня
          - type: state-icon
            entity: binary_sensor.bedroom_motion
          - type: state-icon
            entity: binary_sensor.bedroom_window
  - id: camera
    title: Камеры
    icon: mdi:camera
    cards:
      - type: picture-glance
        title: Зал
        entities:
          - light.livingroom
          - light.livingroom_back
        camera_image: camera.zal
      - type: picture-glance
        title: Спальня
        entities:
          - light.bedroom
          - light.bedroom_back
        camera_image: camera.spalnia
      - type: picture-glance
        title: Кухня
        entities:
          - light.kitchen
          - light.kitchen_back
        camera_image: camera.kukhnia
      - type: picture-glance
        title: Прихожая
        entities:
          - light.hall
        camera_image: camera.prikhozhaia
  - id: home
    title: Дом
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: Освещение
        entities:
          - light.livingroom
          - light.livingroom_back
          - type: divider
          - light.bedroom
          - light.bedroom_back
          - type: divider
          - light.kitchen
          - light.kitchen_back
          - type: divider
          - light.wc
          - type: divider
          - light.corridor
          - type: divider
          - light.bathroom
          - type: divider
          - light.hall
      - type: glance
        title: Пылесос
        #show_name: false
        show_state: false
        entities:
          - script.mamibot_off
          - script.mamibot_on
          - script.mamibot_charge
          - script.mamibot_clean
          - script.mamibot_clean_border
  - id: climate-management
    title: Климат
    icon: mdi:fan
    cards:
      - type: thermostat
        entity: climate.livingroom
      - type: thermostat
        entity: climate.bedroom
      - type: glance
        title: Увлажнитель спальня
        show_name: false
        #show_state: false
        entities:
          - script.humidifier_bedroom_onoff
          - script.humidifier_bedroom_auto
          - script.humidifier_bedroom_light
          - script.humidifier_bedroom_uv
          - script.humidifier_bedroom_ion
  - id: devices
    title: Устройства
    icon: mdi:tablet-cellphone
    badges:
      - device_tracker.phone_oksana
      - device_tracker.phone_drronnie
    cards:
      - type: gauge
        entity: sensor.voltage
        min: 180
        max: 250
        severity:
          yellow: 180
          green: 210
          red: 230
      - type: horizontal-stack
        cards:
          - type: entities
            title: Медиа
            show_header_toggle: false
            entities:
              - device_tracker.router_main
              - device_tracker.router_kitchen
              - device_tracker.router_livingroom
              - device_tracker.media_mibox_livingroom
              - device_tracker.media_ghmini_bedroom
          - type: entities
            title: Серверы
            show_header_toggle: false
            entities:
              - device_tracker.srv_esxi
              - device_tracker.srv_nas
              - device_tracker.srv_db1
      - type: horizontal-stack
        cards:
          - type: entities
            title: Камеры
            show_header_toggle: false
            entities:
              - device_tracker.camera_loft
              - device_tracker.camera_entrance
              - device_tracker.camera_tambour
              - device_tracker.camera_livingroom
              - device_tracker.camera_bedroom
              - device_tracker.camera_cristoph
              - device_tracker.camera_kitchen
              - device_tracker.camera_hall
              - device_tracker.camera_mobile
          - type: entities
            title: IoT
            show_header_toggle: false
            entities:
              - device_tracker.iot_rmpro_livingroom
              - device_tracker.iot_a1_bedroom
              - device_tracker.iot_mp1_kitchen
              - device_tracker.iot_bridge_hall
              - device_tracker.iot_powb1_wc
              - device_tracker.iot_mc1_bedroom
              - device_tracker.iot_th10_kitchen
              - device_tracker.iot_a1_livingroom
              - device_tracker.iot_rmpro_bedroom
  - id: floorplan
    title: План
    icon: mdi:floor-plan
    #panel: true
    cards:
      - type: picture-elements
        image: /local/floorplan/main.png
        elements:
          # living room
          - type: icon
            icon: mdi:cctv
            entity: camera.zal
            tap_action:
              action: more-info
            style:
              left: 7%
              top: 34%
          - type: state-label
            entity: sensor.br_livingroom_temperature
            style:
              left: 20%
              top: 43%
          - type: state-label
            entity: sensor.br_livingroom_humidity
            style:
              left: 20%
              top: 48%
          - type: state-icon
            entity: light.livingroom
            tap_action:
              action: toggle
            style:
              left: 15%
              top: 62%
          - type: state-icon
            entity: light.livingroom_back
            tap_action:
              action: toggle
            style:
              left: 25%
              top: 62%
          # bedroom
          - type: icon
            icon: mdi:cctv
            entity: camera.spalnia
            tap_action:
              action: more-info
            style:
              left: 63%
              top: 10%
          - type: icon
            icon: mdi:cctv
            entity: camera.kristof
            tap_action:
              action: more-info
            style:
              left: 39%
              top: 22%
          - type: state-label
            entity: sensor.br_bedroom_temperature
            style:
              left: 51%
              top: 23%
          - type: state-label
            entity: sensor.br_bedroom_humidity
            style:
              left: 51%
              top: 28%
          - type: state-icon
            entity: light.bedroom
            tap_action:
              action: toggle
            style:
              left: 51%
              top: 42%
          - type: state-icon
            entity: light.bedroom_back
            tap_action:
              action: toggle
            style:
              left: 63%
              top: 22%
          # kitchen
          - type: icon
            icon: mdi:cctv
            entity: camera.kukhnia
            tap_action:
              action: more-info
            style:
              left: 71%
              top: 46%
          - type: state-label
            entity: sensor.kitchen_temperature
            style:
              left: 83%
              top: 16%
          - type: state-label
            entity: sensor.kitchen_humidity
            style:
              left: 83%
              top: 21%
          - type: state-icon
            entity: light.kitchen
            tap_action:
              action: toggle
            style:
              left: 83%
              top: 34%
          - type: state-icon
            entity: light.kitchen_back
            tap_action:
              action: toggle
            style:
              left: 95%
              top: 46%
          # hall
          - type: icon
            icon: mdi:cctv
            entity: camera.prikhozhaia
            tap_action:
              action: more-info
            style:
              left: 41%
              top: 85%
          - type: state-icon
            entity: light.hall
            tap_action:
              action: toggle
            style:
              left: 51%
              top: 85%
          # corridor
          - type: state-icon
            entity: light.corridor
            tap_action:
              action: toggle
            style:
              left: 77%
              top: 72%
          # bathroom
          - type: state-icon
            entity: light.bathroom
            tap_action:
              action: toggle
            style:
              left: 85%
              top: 84%
          # wc
          - type: state-icon
            entity: light.wc
            tap_action:
              action: toggle
            style:
              left: 84%
              top: 59%
          - type: state-icon
            entity: fan.wc_fan
            tap_action:
              action: toggle
            style:
              left: 94%
              top: 59%
  - id: map
    title: Карта
    icon: mdi:map
    panel: true
    cards:
      - type: map
        default_zoom: 13
        entities:
          - device_tracker.google_maps_105861814760109955404
          - device_tracker.google_maps_104258330239786803059
          - zone.home
          - zone.work
          - zone.motherinlaw