title: Andrew and Oksana's home
resources:
  - type: module
    url: /local/custom_ui/weather-card.js?v=0.24
views:
  - id: info
    title: Информация
    icon: mdi:information
    badges:
      - device_tracker.phone_oksana
      - device_tracker.phone_andrew
    cards:
      - entity: weather.dark_sky
        type: 'custom:weather-card'
  - id: camera
    title: Камеры
    icon: mdi:camera
    cards:
      - type: picture-glance
        title: Зал
        entities:
          - light.livingroom
          - light.livingroom_back
        camera_image: camera.zal
      - type: picture-glance
        title: Спальня
        entities:
          - light.bedroom
          - light.bedroom_back
        camera_image: camera.spalnia
      - type: picture-glance
        title: Кухня
        entities:
          - light.kitchen
          - light.kitchen_back
        camera_image: camera.kukhnia
      - type: picture-glance
        title: Прихожая
        entities:
          - light.hall
        camera_image: camera.prikhozhaia
  - id: home
    title: Дом
    icon: 'mdi:home-assistant'
    cards:
      - type: entities
        title: Датчики
        entities:
          - type: state-icon
            entity: binary_sensor.livingroom_motion
          - type: state-icon
            entity: binary_sensor.livingroom_window          
          - type: state-icon
            entity: binary_sensor.livingroom_balcony
      - type: entities
        title: Освещение
        entities:
          - toggle: true
            entity: light.livingroom
          - toggle: true
            entity: light.livingroom_back
          - type: divider
          - toggle: true
            entity: light.bedroom
          - toggle: true
            entity: light.bedroom_back
          - type: divider
          - toggle: true
            entity: light.kitchen
          - toggle: true
            entity: light.kitchen_back
          - type: divider
          - toggle: true
            entity: light.wc
          - type: divider
          - toggle: true
            entity: light.corridor
          - type: divider
          - toggle: true
            entity: light.bathroom
          - type: divider
          - toggle: true
            entity: light.hall
  - id: weather
    title: Погода
    icon: 'mdi:weather-cloudy'
    cards:
      - entity: weather.dark_sky
        type: 'custom:weather-card'
      - type: entities
        entities:
          - type: section
            label: Улица
          - sensor.darksky_temperature
          - sensor.darksky_humidity
          - type: section
            label: Спальня
          - sensor.br_bedroom_temperature
          - sensor.br_bedroom_humidity
          - type: section
            label: Зал
          - sensor.br_livingroom_temperature
          - type: section
            label: Кухня
          - sensor.kitchen_temperature
          - sensor.kitchen_humidity
      - type: history-graph
        title: Температура
        entities:
          - entity: sensor.darksky_temperature
            name: Улица
          - entity: sensor.br_livingroom_temperature
            name: Зал
          - entity: sensor.br_bedroom_temperature
            name: Спальня
          - entity: sensor.kitchen_temperature
            name: Кухня
      - type: history-graph
        title: Влажность
        entities:
          - entity: sensor.darksky_humidity
            name: Улица
          - entity: sensor.br_bedroom_humidity
            name: Спальня
          - entity: sensor.kitchen_humidity
            name: Кухня
      - type: iframe
        url: >-
          https://embed.windy.com/embed2.html?lat=50.455&lon=30.524&zoom=10&overlay=wind&location=coordinates
        aspect_ratio: 90%
  - id: devices
    title: Устройства
    icon: mdi:tablet-cellphone
    badges:
      - device_tracker.phone_oksana
      - device_tracker.phone_andrew
    cards:
      - type: glance
        title: Медиа
        show_state: false
        entities:
          - device_tracker.router_main
          - device_tracker.router_kitchen
          - device_tracker.router_livingroom
          - device_tracker.media_mibox_livingroom
          - device_tracker.media_ghmini_bedroom
      - type: glance
        title: Камеры
        show_state: false
        entities:
          - entity: device_tracker.camera_loft
            name:   Чердак
          - entity: device_tracker.camera_entrance
            name:   Подъезд
          - entity: device_tracker.camera_tambour
            name:   Тамбур
          - entity: device_tracker.camera_livingroom
            name:   Зал
          - entity: device_tracker.camera_bedroom
            name:   Спальня
          - entity: device_tracker.camera_cristoph
            name:   Кристоф
          - entity: device_tracker.camera_kitchen
            name:   Кухня
          - entity: device_tracker.camera_hall
            name:   Прихожая
          - entity: device_tracker.camera_mobile
            name:   Переносная
      - type: glance
        title: IoT
        show_state: false
        entities:
          - device_tracker.iot_rmpro_livingroom
          - device_tracker.iot_a1_bedroom
          - device_tracker.iot_mp1_kitchen
          - device_tracker.iot_bridge_hall
          - device_tracker.iot_powb1_wc
          - device_tracker.iot_mc1_bedroom
          - device_tracker.iot_th10_kitchen
