title: Дом Андрея и Оксаны
resources:
  - type: module
    url: /local/custom_ui/weather-card.js?v=0.24
views:
  - id: climate
    title: Климат
    icon: mdi:weather-cloudy
    cards:
      - entity: weather.dark_sky
        type: custom:weather-card
      - type: iframe
        url: >-
          https://embed.windy.com/embed2.html?lat=50.455&lon=30.524&zoom=10&overlay=wind&location=coordinates
        aspect_ratio: 90%
      - type: entities
        entities:
          - type: section
            label: Улица
          - sensor.dark_sky_temperature
          - sensor.dark_sky_humidity
          - sensor.dark_sky_pressure
          - type: section
            label: Спальня
          - sensor.br_bedroom_temperature
          - sensor.br_bedroom_humidity
          - type: section
            label: Зал
          - sensor.br_livingroom_temperature
          - sensor.br_livingroom_humidity
          - type: section
            label: Кухня
          - sensor.kitchen_temperature
          - sensor.kitchen_humidity
      - type: history-graph
        title: Температура
        entities:
          - entity: sensor.br_livingroom_temperature
            name: Зал
          - entity: sensor.br_bedroom_temperature
            name: Спальня
          - entity: sensor.kitchen_temperature
            name: Кухня
      - type: history-graph
        title: Влажность
        entities:
          - entity: sensor.br_livingroom_humidity
            name: Зал
          - entity: sensor.br_bedroom_humidity
            name: Спальня
          - entity: sensor.kitchen_humidity
            name: Кухня
  - id: security
    title: Информация
    icon: mdi:shield-home
    badges:
      - device_tracker.phone_oksana
      - device_tracker.phone_drronnie
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.ha_alarm
        name: Охрана
        states:
          - arm_away
      - type: entities
        title: Датчики
        show_header_toggle: false
        entities:
          - type: section
            label: Зал
          - type: state-icon
            entity: binary_sensor.livingroom_motion
          - type: state-icon
            entity: binary_sensor.livingroom_window          
          - type: state-icon
            entity: binary_sensor.livingroom_balcony
          - type: section
            label: Прихожая
          - type: state-icon
            entity: binary_sensor.hall_motion
          - type: state-icon
            entity: binary_sensor.hall_entrance
          - type: section
            label: Кухня
          - type: state-icon
            entity: binary_sensor.kitchen_window          
          - type: section
            label: Спальня
          - type: state-icon
            entity: binary_sensor.bedroom_window
          - type: state-icon
            entity: binary_sensor.bedroom_motion
  - id: camera
    title: Камеры
    icon: mdi:camera
    cards:
      - type: picture-glance
        title: Зал
        entities:
          - light.livingroom
          - light.livingroom_back
        camera_image: camera.zal
      - type: picture-glance
        title: Спальня
        entities:
          - light.bedroom
          - light.bedroom_back
        camera_image: camera.spalnia
      - type: picture-glance
        title: Кухня
        entities:
          - light.kitchen
          - light.kitchen_back
        camera_image: camera.kukhnia
      - type: picture-glance
        title: Прихожая
        entities:
          - light.hall
        camera_image: camera.prikhozhaia
  - id: home
    title: Дом
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: Освещение
        entities:
          - light.livingroom
          - light.livingroom_back
          - type: divider
          - light.bedroom
          - light.bedroom_back
          - type: divider
          - light.kitchen
          - light.kitchen_back
          - type: divider
          - light.wc
          - type: divider
          - light.corridor
          - type: divider
          - light.bathroom
          - type: divider
          - light.hall
  - id: climate-management
    title: Климат
    icon: mdi:air-conditioner
    cards:
      - type: thermostat
        entity: climate.livingroom
      - type: thermostat
        entity: climate.bedroom
      - type: entities
        title: Увлажнитель спальня
        show_header_toggle: false
        entities:
          - script.humidifier_bedroom_onoff
          - script.humidifier_bedroom_auto
          - script.humidifier_bedroom_light
          - script.humidifier_bedroom_uv
          - script.humidifier_bedroom_ion
  - id: devices
    title: Устройства
    icon: mdi:tablet-cellphone
    badges:
      - device_tracker.phone_oksana
      - device_tracker.phone_drronnie
    cards:
      - type: gauge
        entity: sensor.voltage
        min: 180
        max: 250
      - type: glance
        title: Медиа
        show_state: false
        entities:
          - device_tracker.router_main
          - device_tracker.router_kitchen
          - device_tracker.router_livingroom
          - device_tracker.media_mibox_livingroom
          - device_tracker.media_ghmini_bedroom
      - type: glance
        title: Камеры
        show_state: false
        entities:
          - device_tracker.camera_loft
          - device_tracker.camera_entrance
          - device_tracker.camera_tambour
          - device_tracker.camera_livingroom
          - device_tracker.camera_bedroom
          - device_tracker.camera_cristoph
          - device_tracker.camera_kitchen
          - device_tracker.camera_hall
          - device_tracker.camera_mobile
      - type: glance
        title: IoT
        show_state: false
        entities:
          - device_tracker.iot_rmpro_livingroom
          - device_tracker.iot_a1_bedroom
          - device_tracker.iot_mp1_kitchen
          - device_tracker.iot_bridge_hall
          - device_tracker.iot_powb1_wc
          - device_tracker.iot_mc1_bedroom
          - device_tracker.iot_th10_kitchen
          - device_tracker.iot_a1_livingroom
          - device_tracker.iot_rmpro_bedroom
      - type: glance
        title: Серверы
        show_state: false
        entities:
          - device_tracker.srv_esxi
          - device_tracker.srv_nas
          - device_tracker.srv_db1
