title: Дом Андрея и Оксаны
resources:
  - type: module
    url: /local/custom_ui/weather-card.js?v=0.24
  - type: module
    url: /local/custom_ui/mini-media-player-bundle.js?v=1.2.1
views:
  - id: climate
    title: Климат
    icon: mdi:weather-cloudy
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Автоматизация
            show_header_toggle: false
            entities:
              - input_boolean.automation
              - input_boolean.automation_light
              - input_boolean.automation_exhaust
              - input_boolean.automation_temperature
          - entity: weather.dark_sky
            type: custom:weather-card
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: glance
                title: Улица
                show_name: false
                entities:
                  - sensor.dark_sky_temperature
                  - sensor.dark_sky_humidity
              - type: glance
                title: Среднее
                show_name: false
                entities:
                  - sensor.flat_temperature
                  - sensor.flat_humidity
          - type: horizontal-stack
            cards:
              - type: glance
                title: Зал
                show_name: false
                entities:
                  - sensor.livingroom_temperature
                  - sensor.livingroom_humidity
              - type: glance
                title: Спальня
                show_name: false
                entities:
                  - sensor.bedroom_temperature
                  - sensor.bedroom_humidity
          - type: horizontal-stack
            cards:
              - type: glance
                title: Кухня
                show_name: false
                entities:
                  - sensor.kitchen_temperature
                  - sensor.kitchen_humidity
              - type: glance
                title: Ванная
                show_name: false
                entities:
                  - sensor.bathroom_temperature
                  - sensor.bathroom_humidity
          - type: horizontal-stack
            cards:
              - type: glance
                title: Прихожая
                show_name: false
                entities:
                  - sensor.hall_temperature
                  - sensor.hall_humidity
              - type: glance
                title: Балкон
                show_name: false
                entities:
                  - sensor.balcony_temperature
                  - sensor.balcony_humidity
      - type: vertical-stack
        cards:
          - type: history-graph
            title: Температура
            entities:
              - entity: sensor.livingroom_temperature
                name: Зал
              - entity: sensor.bedroom_temperature
                name: Спальня
              - entity: sensor.kitchen_temperature
                name: Кухня
              - entity: sensor.bathroom_temperature
                name: Ванная
              - entity: sensor.flat_temperature
                name: Средняя
          - type: history-graph
            title: Влажность
            entities:
              - entity: sensor.livingroom_humidity
                name: Зал
              - entity: sensor.bedroom_humidity
                name: Спальня
              - entity: sensor.kitchen_humidity
                name: Кухня
              - entity: sensor.bathroom_humidity
                name: Ванная
              - entity: sensor.flat_humidity
                name: Средняя
  - id: home
    title: Дом
    icon: mdi:home-assistant
    cards:
      - type: entities
        title: Освещение
        entities:
          - group.light_livingroom
          - group.light_bedroom
          - group.light_kitchen
          - group.light_hall
          - group.light_corridor
          - group.light_wc
          - group.light_bathroom
      - type: entities
        title: Освещение
        show_header_toggle: false
        entities:
          - light.livingroom
          - light.livingroom_back
          - type: divider
          - light.bedroom
          - light.bedroom_back
          - type: divider
          - light.kitchen
          - light.kitchen_back
          - type: divider
          - light.wc
          - type: divider
          - light.corridor
          - type: divider
          - light.bathroom
          - type: divider
          - light.hall
          - light.hall_back
      - type: glance
        title: Пылесос
        #show_name: false
        show_state: false
        entities:
          - script.mamibot_off
          - script.mamibot_on
          - script.mamibot_charge
          - script.mamibot_clean
          - script.mamibot_clean_border
  - id: climate-management
    title: Климат
    icon: mdi:fan
    cards:
      - type: vertical-stack
        cards:
          - type: history-graph
            title: Зал
            entities:
              - sensor.livingroom_temperature
              - sensor.livingroom_humidity
          - type: thermostat
            entity: climate.livingroom_ac
      - type: vertical-stack
        cards:
          - type: history-graph
            title: Спальня
            entities:
              - sensor.bedroom_temperature
              - sensor.bedroom_humidity
          - type: thermostat
            entity: climate.bedroom_ac
          - type: glance
            title: Увлажнитель спальня
            show_state: false
            entities:
              - entity: script.humidifier_bedroom_onoff
                tap_action:
                  action: toggle
              - entity: script.humidifier_bedroom_auto
                tap_action:
                  action: toggle
              - entity: script.humidifier_bedroom_light
                tap_action:
                  action: toggle
              - entity: script.humidifier_bedroom_uv
                tap_action:
                  action: toggle
              - entity: script.humidifier_bedroom_ion
                tap_action:
                  action: toggle
  - id: multimedia
    title: Мультимедиа
    icon: mdi:play-circle-outline
    cards:
      - type: custom:mini-media-player
        entity: media_player.bedroom_ghmini
      - type: custom:mini-media-player
        entity: media_player.livingroom_mitvbox
      - type: entities
        title: Экран
        show_header_toggle: false
        entities:
          - cover.projector_screen

  # - id: camera
  #   title: Камеры
  #   icon: mdi:camera
  #   cards:
  #     - type: picture-glance
  #       title: Тамбур
  #       entities: []
  #       camera_image: camera.tambur
  #     - type: picture-glance
  #       title: Прихожая
  #       entities:
  #         - light.hall
  #       camera_image: camera.prikhozhaia
  #     - type: picture-glance
  #       title: Зал
  #       entities:
  #         - light.livingroom
  #         - light.livingroom_back
  #       camera_image: camera.zal
  #     - type: picture-glance
  #       title: Спальня
  #       entities:
  #         - light.bedroom
  #         - light.bedroom_back
  #       camera_image: camera.spalnia
  #     - type: picture-glance
  #       title: Кристоф
  #       entities: []
  #       camera_image: camera.kristof
  #     - type: picture-glance
  #       title: Кухня
  #       entities:
  #         - light.kitchen
  #         - light.kitchen_back
  #       camera_image: camera.kukhnia
  - id: security
    title: Информация
    icon: mdi:shield
    cards:
      - type: entities
        title: Охрана
        show_header_toggle: false
        entities:
          - type: section
            label: Зал
          - binary_sensor.livingroom_motion
          - binary_sensor.livingroom_window          
          - binary_sensor.livingroom_balcony
          - type: section
            label: Прихожая
          - binary_sensor.hall_motion
          - binary_sensor.hall_entrance
          - type: section
            label: Кухня
          - binary_sensor.kitchen_motion
          - binary_sensor.kitchen_window
          - type: section
            label: Спальня
          - binary_sensor.bedroom_motion
          - binary_sensor.bedroom_window
      - type: entities
        title: Люди
        show_header_toggle: false
        entities:
          - device_tracker.phone_oksana
          - device_tracker.phone_drronnie
      - type: entities
        title: Датчики
        show_header_toggle: false
        entities:
          - type: section
            label: Кухня
          - binary_sensor.kitchen_waterleak
          - binary_sensor.kitchen_smoke
          - type: section
            label: Туалет
          - binary_sensor.wc_waterleak
          - type: section
            label: Ванная
          - binary_sensor.bathroom_waterleak
  - id: devices
    title: Устройства
    icon: mdi:tablet-cellphone
    cards:
      - type: history-graph
        title: Температура
        entities:
          - entity: sensor.serverbox_temperature
            name: Серверный шкаф
          - entity: sensor.ups_battery_temperature
            name: Батарея ИБП
      - type: horizontal-stack
        cards:
          - type: entities
            title: Показатели
            show_header_toggle: false
            entities:
              - entity: sensor.serverbox_temperature
                name: Серверный шкаф
              - entity: sensor.ups_battery_temperature
                name: Батарея ИБП
              - sensor.ups_battery_charge
              - sensor.ups_input_voltage
              - sensor.ups_output_voltage
          - type: entities
            title: Датчики
            show_header_toggle: false
            entities:
              - entity: sensor.livingroom_window_battery
                name: Зал окно
              - entity: sensor.livingroom_balcony_battery
                name: Зал балкон
              - entity: sensor.livingroom_motion_battery
                name: Зал движение
              - entity: sensor.livingroom_cube_battery
                name: Зал куб
              - type: divider
              - entity: sensor.bedroom_window_battery
                name: Спальня окно
              - entity: sensor.bedroom_motion_battery
                name: Спальня движение
              - type: divider
              - entity: sensor.kitchen_window_battery
                name: Кухня окно
              - entity: sensor.kitchen_motion_battery
                name: Кухня движение
              - entity: sensor.kitchen_waterleak_battery
                name: Кухня утечка
              - type: divider
              - entity: sensor.wc_waterleak_battery
                name: Туалет утечка
              - type: divider
              - entity: sensor.bathroom_temperature_battery
                name: Ванная утечка
              - type: divider
              - entity: sensor.hall_entrance_battery
                name: Прихожая вход
              - entity: sensor.hall_motion_battery
                name: Прихожая движение
              - entity: sensor.hall_temperature_battery
                name: Прихожая температура
              - type: divider
              - entity: sensor.balcony_temperature_battery
                name: Балкон температура
              - type: divider
              - entity: sensor.serverbox_temperature_battery
                name: Серверный шкаф температура
      - type: horizontal-stack
        cards:
          - type: entities
            title: Медиа
            show_header_toggle: false
            entities:
              - device_tracker.phone_oksana
              - device_tracker.phone_drronnie
              - type: divider
              - device_tracker.srv_switch
              - device_tracker.srv_router_main
              - device_tracker.srv_router_hall
              - device_tracker.srv_router_kitchen
              - device_tracker.srv_router_livingroom
              - device_tracker.media_mibox_livingroom
              - device_tracker.media_ghmini_bedroom
          - type: entities
            title: Серверы
            show_header_toggle: false
            entities:
              - device_tracker.srv_esxi
              - device_tracker.srv_nas1
              - device_tracker.srv_nas2
              - device_tracker.srv_db1
      - type: horizontal-stack
        cards:
          - type: entities
            title: Камеры
            show_header_toggle: false
            entities:
              - device_tracker.cam_loft
              - device_tracker.cam_entrance
              - device_tracker.cam_tambour
              - device_tracker.cam_livingroom
              - device_tracker.cam_balcony
              - device_tracker.cam_bedroom
              - device_tracker.cam_cristoph
              - device_tracker.cam_kitchen
              - device_tracker.cam_hall
              - device_tracker.cam_radunska
              - device_tracker.cam_balzaka
          - type: entities
            title: IoT
            show_header_toggle: false
            entities:
              - device_tracker.iot_rmpro_livingroom
              - device_tracker.iot_a1_livingroom
              - device_tracker.iot_rmpro_bedroom
              - device_tracker.iot_a1_bedroom
              - device_tracker.iot_saltlamp_bedroom
              - device_tracker.iot_th10_kitchen
              - device_tracker.iot_mp1_kitchen
              - device_tracker.iot_th10_bathroom
              - device_tracker.iot_bridge_hall
              - device_tracker.iot_powr2_wc
              - device_tracker.iot_ajax
              - device_tracker.iot_mamibot
              - device_tracker.iot_zigbee_hall