external_armaway:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfout/set
        payload: C001016C18000CEBA8
external_armhome:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfout/set
        payload: C001016C18000CEBA2
external_disarm:
  sequence:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfout/set
        payload: C001016C18000CEBA4
# external_panic:
#   sequence:
#     - service: mqtt.publish
#       data_template:
#         topic: bridge/rfout/set
#         payload: C001016B18000CEBA1

alarm_telegram:
  sequence:
    - service: notify.telegram
      data_template:
        message: "{{ message }}"
    - service: notify.telegram
      data:
        message: photos
        data:
          photo:
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.zal?api_password=80c0587b93750a246a22166bc0e9b6df
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.kukhnia?api_password=80c0587b93750a246a22166bc0e9b6df
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.spalnia?api_password=80c0587b93750a246a22166bc0e9b6df
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.prikhozhaia?api_password=80c0587b93750a246a22166bc0e9b6df
