alarm_armdisarm:
  sequence:
    - service: notify.telegram
      data_template:
        message: "{{ message }}"
    - service: notify.telegram
      data:
        message: photos
        data:
          photo:
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.tambour?api_password=80c0587b93750a246a22166bc0e9b6df
alarm_alert_view:
  sequence:
    - service: notify.telegram
      data_template:
        message: "{{ message }}"
    - service: notify.telegram
      data:
        message: photos
        data:
          photo:
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.livingroom?api_password=80c0587b93750a246a22166bc0e9b6df
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.kitchen?api_password=80c0587b93750a246a22166bc0e9b6df
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.bedroom?api_password=80c0587b93750a246a22166bc0e9b6df
            - url: http://127.0.0.1:8123/api/camera_proxy/camera.hall?api_password=80c0587b93750a246a22166bc0e9b6df
alarm_alert:
  sequence:
    - service: notify.telegram
      data_template:
        message: "{{ message }}"
