device_tracker:
  - platform: ping
    interval_seconds: 10
    consider_home: 180
    track_new_devices: true
    hosts:
      srv_router_main:        192.168.1.1
      srv_switch:             192.168.1.2
      srv_router_hall:        192.168.1.252
      srv_router_kitchen:     192.168.1.253
      srv_router_livingroom:  192.168.1.254
      srv_esxi:               192.168.1.3
      srv_nas1:               192.168.1.4
      srv_nas2:               192.168.1.5
      srv_db1:                192.168.1.6
      phone_oksana:           192.168.1.21
      phone_drronnie:         192.168.1.23
      cam_livingroom:         192.168.1.41
      cam_tambour:            192.168.1.42
      cam_loft:               192.168.1.43
      cam_entrance:           192.168.1.44
      cam_kitchen:            192.168.1.45
      cam_cristoph:           192.168.1.46
      cam_hall:               192.168.1.47
      cam_bedroom:            192.168.1.48
      cam_balcony:            192.168.1.49
      cam_radunska:           192.168.1.50
      cam_balzaka:            192.168.1.51
      cam_yard:               192.168.1.52
      cam_23entrance:         192.168.31.160
      cam_23flat:             192.168.31.229
      cam_23vitalik:          192.168.31.128
      iot_a1_livingroom:      192.168.1.61
      iot_rmpro_livingroom:   192.168.1.62
      iot_th10_server:        192.168.1.63
      iot_rmpro_bedroom:      192.168.1.64
      iot_a1_bedroom:         192.168.1.65
      iot_mp1_kitchen:        192.168.1.66
      iot_bridge_hall:        192.168.1.69
      iot_powr2_wc:           192.168.1.70
      iot_th10_kitchen:       192.168.1.71
      iot_saltlamp_bedroom:   192.168.1.73
      iot_ajax:               192.168.1.74
      iot_mamibot:            192.168.1.75
      iot_zigbee_hall:        192.168.1.76
      media_mibox_livingroom: 192.168.1.91
      media_ghmini_bedroom:   192.168.1.92
      media_firetv_bedroom:   192.168.1.92
  - platform: google_maps
    username: !secret google_login
    password: !secret google_pass
  # - platform: bluetooth_tracker
  # - platform: googlehome
  #   host: 192.168.1.92

homeassistant:
  customize:
    device_tracker.phone_oksana:
      friendly_name: Оксана
      friendly_type: Телефон
      icon: mdi:cellphone-android
    device_tracker.phone_drronnie:
      friendly_name: Андрей
      friendly_type: Телефон
      icon: mdi:cellphone-android
    device_tracker.srv_switch:
      friendly_name: Главный
      friendly_type: Свитч
      icon: mdi:switch
    device_tracker.srv_router_main:
      friendly_name: Главный
      friendly_type: Роутер
      icon: mdi:router-wireless
    device_tracker.srv_router_hall:
      friendly_name: Прихожая
      friendly_type: Роутер
      icon: mdi:router-wireless
    device_tracker.srv_router_kitchen:
      friendly_name: Кухня
      friendly_type: Роутер
      icon: mdi:router-wireless
    device_tracker.srv_router_livingroom:
      friendly_name: Зал
      friendly_type: Роутер
      icon: mdi:router-wireless
    device_tracker.cam_livingroom:
      friendly_name: Зал
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_tambour:
      friendly_name: Тамбур
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_loft:
      friendly_name: Чердак
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_entrance:
      friendly_name: Подъезд
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_kitchen:
      friendly_name: Кухня
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_cristoph:
      friendly_name: Кристоф
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_hall:
      friendly_name: Прихожая
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_bedroom:
      friendly_name: Спальня
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_balcony:
      friendly_name: Балкон
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_radunska:
      friendly_name: Радунская
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_balzaka:
      friendly_name: Бальзака
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.cam_yard:
      friendly_name: Двор
      friendly_type: Камера
      icon: mdi:cctv
    device_tracker.iot_rmpro_livingroom:
      friendly_name: Зал
      friendly_type: RMPro
      icon: mdi:remote
    device_tracker.iot_a1_bedroom:
      friendly_name: Спальня
      friendly_type: A1
      icon: mdi:thermometer
    device_tracker.iot_mp1_kitchen:
      friendly_name: Кухня MP1
      friendly_type: MP1
      icon: mdi:power-socket-eu
    device_tracker.iot_bridge_hall:
      friendly_name: Прихожая
      friendly_type: RF Bridge
      icon: mdi:remote
    device_tracker.iot_zigbee_hall:
      friendly_name: Прихожая
      friendly_type: ZigBee Bridge
      icon: mdi:remote
    device_tracker.iot_powr2_wc:
      friendly_name: Туалет
      friendly_type: POWR2
      icon: mdi:power-socket-eu
    device_tracker.iot_saltlamp_bedroom:
      friendly_name: Спальня
      friendly_type: SP1
      icon: mdi:lightbulb
    device_tracker.iot_th10_kitchen:
      friendly_name: Кухня
      friendly_type: TH10
      icon: mdi:thermometer
    device_tracker.iot_th10_server:
      friendly_name: Ванная
      friendly_type: TH10
      icon: mdi:thermometer
    device_tracker.iot_a1_livingroom:
      friendly_name: Зал
      friendly_type: A1
      icon: mdi:thermometer
    device_tracker.iot_rmpro_bedroom:
      friendly_name: Спальня
      friendly_type: RMPro
      icon: mdi:remote
    device_tracker.iot_ajax:
      friendly_name: Ajax
      friendly_type: Хаб
      icon: mdi:shield-home
    device_tracker.iot_mamibot:
      friendly_name: Mamibot
      friendly_type: Пылесос
      icon: mdi:robot-vacuum

    device_tracker.media_mibox_livingroom:
      friendly_name: Зал
      icon: mdi:television
    device_tracker.media_ghmini_bedroom:
      friendly_name: Спальня
      icon: mdi:google-home
    device_tracker.media_firetv_livingroom:
      friendly_name: Зал
      icon: mdi:television

    device_tracker.srv_esxi:
      friendly_name: ESXi
      icon: mdi:server
    device_tracker.srv_nas1:
      friendly_name: NAS1
      icon: mdi:server
    device_tracker.srv_nas2:
      friendly_name: NAS2
      icon: mdi:server
    device_tracker.srv_db1:
      friendly_name: DB1
      icon: mdi:server

    device_tracker.google_maps_105861814760109955404:
      friendly_name: Андрей
    device_tracker.google_maps_104258330239786803059:
      friendly_name: Оксана
