sensor:
  - platform: template
    sensors:
      kitchen_humidity_diff:
        unit_of_measurement: "%"
        entity_id:
          - sensor.flat_humidity
          - sensor.kitchen_humidity
        value_template: >- 
          {{ (((states.sensor.kitchen_humidity.state | float) - (states.sensor.flat_humidity.state | float)) / (states.sensor.flat_humidity.state | float) * 100) | round(0) }}
      bathroom_humidity_diff:
        unit_of_measurement: "%"
        entity_id:
          - sensor.flat_humidity
          - sensor.bathroom_humidity
        value_template: >- 
          {{ (((states.sensor.bathroom_humidity.state | float) - (states.sensor.flat_humidity.state | float)) / (states.sensor.flat_humidity.state | float) * 100) | round(0) }}