sensor:
  - platform: template
    sensors:
      kitchen_humidity_diff:
        unit_of_measurement: "%"
        entity_id:
          - sensor.flat_humidity
          - sensor.kitchen_humidity
        value_template: >- 
          {{ (((states.sensor.kitchen_humidity.state | float) - (states.sensor.flat_humidity.state | float)) / (states.sensor.flat_humidity.state | float) * 100) | round(0) }}
      bathroom_humidity_diff:
        unit_of_measurement: "%"
        entity_id:
          - sensor.flat_humidity
          - sensor.bathroom_humidity
        value_template: >- 
          {{ (((states.sensor.bathroom_humidity.state | float) - (states.sensor.flat_humidity.state | float)) / (states.sensor.flat_humidity.state | float) * 100) | round(0) }}

automation:
  - alias: exhaust_kitchen_on
    initial_state: 'false'
    trigger:
      platform: numeric_state
      entity_id: sensor.kitchen_humidity_diff
      above: 10
    condition:
      - condition: state
        entity_id: input_boolean.automation_exhaust
        state: 'on'
    action:
      service: script.alarm_alert
      data_template:
        message: "Вытяжка в кухне включена."

  - alias: exhaust_kitchen_off
    initial_state: 'false'
    trigger:
      platform: numeric_state
      entity_id: sensor.kitchen_humidity_diff
      below: 8
    condition:
      - condition: state
        entity_id: input_boolean.automation_exhaust
        state: 'on'
    action:
      service: script.alarm_alert
      data_template:
        message: "Вытяжка в кухне выключена."

  - alias: exhaust_bathroom_on
    initial_state: 'false'
    trigger:
      platform: numeric_state
      entity_id: sensor.bathroom_humidity_diff
      above: 10
    condition:
      - condition: state
        entity_id: input_boolean.automation_exhaust
        state: 'on'
    action:
      service: script.alarm_alert
      data_template:
        message: "Вытяжка в ванной включена."

  - alias: exhaust_bathroom_off
    initial_state: 'false'
    trigger:
      platform: numeric_state
      entity_id: sensor.bathroom_humidity_diff
      below: 8
    condition:
      - condition: state
        entity_id: input_boolean.automation_exhaust
        state: 'on'
    action:
      service: script.alarm_alert
      data_template:
        message: "Вытяжка в ванной выключена."