script:
  humidifier_bedroom_onoff:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgDqACwLLAsQKCsMKwwQJxAnLAssCxAoECcPAAEuKwwrDA8oLAssCxEnECcrDCsMECcQJxAAAS0rDCwLECgqDSoNDygPKCsMKwwPKA8pDwABLSsNKg0NKikOKwwPKA8oKwwrDQ0qDygPAAEuKQ4pDg4pKQ4pDw8oDygpDikODSoPKA8AAS4rDCsNDygrDCsMDygPKCsMLAsQKA8oEAABLSsMKwwQJywLLAsPKBAnLAssCxEnECcQAAEtLAssCxAnLAssCxAnECcsCywMDygPKA8AAS4rDCsMDygrDCsMECgPKCsMKwwNKg8oDwANBQAAAAAAAAAAAAAAAAAA"
  humidifier_bedroom_night:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgDQACkOKQ4NKikOKQ4OKg0qDSoNKikODikOAAEvKQ4pDw0qKQ4pDg0qDSoOKQ4qKg0OKQ0AATAqDSkODSopDikODioNKg0qDSopDg0qDQABMCoNKg0OKSoNKg4NKg0qDikOKSoNDikPAAEuKQ4qDg4pKg0qDQ4pDSoNKg4pKg0PKQ0AATAqDSkODSopDikODioNKg0qDSopDg0qDQABMCkOKQ4OKSkOKQ4OKg0qDSoNKikODSoOAAEvKQ4rDBAoKg0pDg0qDSoPKA8oKwwPKQ4ADQUAAAAAAAAAAA=="
  humidifier_bedroom_auto:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgDQACkOKQ4NKikOKQ4OKg0qDSoNKg8oKwwNAAEwKwwpDg4qKg0qDQ8oDygNKg8oDygrDBAAAS0pDykODSopDikODSoOKQ4pDioNKikODQABMCkOKQ4NKikOKQ4OKg0qDSoNKg0qKQ4OAAEvKQ4pDg4qKA8pDg0qDSoNKg4pDiooDw0AATApDikODSopDikODikOKQ4qDSoNKikODQABMCkOKQ4OKSkOKQ4OKg0qDSoNKg0qKQ4OAAEvKQ4pDg4qKQ4pDg0qDSoNKg4pDiooDw0ADQUAAAAAAAAAAA=="
  humidifier_bedroom_kids:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgCGAA4ABwkpDikODSoqDSoNDSoNKg0qDikqDSoNDgABLyoNKg0OKikOKQ4NKg0qDSoNKioNKg0OAAEvKg0qDQ4qKQ4pDg0qDSoNKg0qKQ4qDQ4AAS8pDioNDiopDikODSoNKg0qDSoqDSoNDgABLyoNKg0OKikOKQ4NKg0qDSoOKSoNKg4NAA0FAAA="
  humidifier_bedroom_heart:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgCcACoNKg0NKioNKg0PKA4pDioNKioNDSoqAAETKQ4pDg0qKQ4pDg4qDSoNKg0qKQ4NKikAARQpDikODikpDikPDSoNKg0qDSopDg4pKQABFCkPKQ4NKikOKQ4NKg4pDikOKigPDSopAAEUKQ4pDg0qKQ4pDg0qDikOKQ4qKA8NKikAARQpDikODSopDikODSoNKhAnECgqDQ8oLAANBQAAAAAAAAAAAAAAAAJgCcACoNKg0NKioNKg0PKA4pDioNKioNDSoqAAETKQ4pDg0qKQ4pDg4qDSoNKg0qKQ4NKikAARQpDikODikpDikPDSoNKg0qDSopDg4pKQABFCkPKQ4NKikOKQ4NKg4pDikOKigPDSopAAEUKQ4pDg0qKQ4pDg0qDikOKQ4qKA8NKikAARQpDikODSopDikODSoNKhAnECgqDQ8oLAANBQAAAAAAAAAAAAAAAA=="
  humidifier_bedroom_touch:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgDQACkOKg0NKioNKg0OKQ4pDiooDw0qKg0qAAETKg0qDQ0qKg0qDQ4pDioNKikODSoqDSoAARMqDSoNDikqDSoODSoNKg0qKg0NKioNKgABEyoNKQ4OKikOKQ4NKg0qDSoqDQ4pKg0qAAETKg0qDg0qKQ4qDQ0qDSoOKSoNDikqDikAARQpDikODSoqDSoNDikOKQ4qKQ4NKikOKgABEyoNKg0NKioNKg0OKhAnDSopDg0qKg0qAAETKg0qDQ4qKQ4pDg0qDSoNKioNDiksCyoADQUAAAAAAAAAAA=="
  humidifier_bedroom_light:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgDQACoNKg0OKSoNKg0OKQ4pKQ8NKioNDSoNAAEwKQ4pDg0qKQ4pDg4qDSopDg0qKQ4NKg0AATAqDSkODikpDikPDSoNKikODSopDg0qDQABMCoNKg0NKikOKg0OKg0qKQ4NKioNDikOAAEvKg0qDQ8oKg0qDQ4qDikqDQ4pKg0OKQ4AAS8qDSoNDikqDSoNDygPKCoODikqDQ4pDgABLysMKg0OKSoNKg0PKA8oKg0PKCoNDykOAAEuKwwqDQ8oKg0rDQ4pDikqDQ4pKg0OKQ4ADQUAAAAAAAAAAA=="
  humidifier_bedroom_time:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgCcACoNKg0PKSsMKg0OKQ4pDygrDA8pDikOAAEvKg0qDQ4pKg0qDQ8pDSoNKioNDikOKQ8AAS4qDSoNDioqDSoNDikOKQ4pKg0PKA8pDgABLyoNKg0OKSoNKg0PKA8pDikqDQ4pDikPAAEuKwwrDA8pKg0qDQ4pDygPKCsMDykOKQ4AAS8qDSsMDygqDSoNDykOKQ4pKwwPKA8oDwANBQAAAAAAAAAAAAAAAA=="
  humidifier_bedroom_heat:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgCcAC0MKwwPKCsMLAssCxEnECcQJw8oKwwsAAERKwwqDQ0qKQ4qDSoNDikOKg0qDSopDioAARMqDSoNDSoqDSoNKg0OKg0qDSoNKioNKgABEyoNKg0OKSoNKg0qDQ4qDSoNKg0qKg0qAAETKg0qDQ4pKg0qDikODSoNKg0qDSoqDSoAARMqDSoNDikqDSoOKQ4NKg0qDSoNKiwLLAANBQAAAAAAAAAAAAAAAA=="
  humidifier_bedroom_uv:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgCcACoNKQ4NKikOKQ4OKg0qDSoqDQ4pDSopAAEUKQ4pDg4pKQ4pDg4qDSoNKikODSoNKikAARQpDikODiooDygPDSoNKg0qKQ4OKQ4pKQABFCkPKQ4NKikOKQ4NKg4pDikrDBAoDygqAAESLAwrDBAnKwwrDA8oDygQJywLECcQJysAARIrDCsNDygrDCwLDygPKBAnLAsRJxAnKwANBQAAAAAAAAAAAAAAAA=="
  humidifier_bedroom_ion:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgC2ACsMKwwQJysMLAsQJxAoDygPKA8oKwwrAAESKwwrDA8oKwwqDRAnDygQKA4pDikqDSoAARAuDCoNDikpDikODioNKg0qDSoNKikOKQABFCkOKQ4OKigPKQ4NKg0qDSoNKg4pKQ4pAAEUKQ8pDg0qKQ4pDg0qDikOKQ4qDSopDikAARQpDikODSopDikODioNKg0qDSoNKikOKQABFCoNKwwQJykOKg0PKQ4pDygOKRAnKwwrAA0FAAAJgC2ACsMKwwQJysMLAsQJxAoDygPKA8oKwwrAAESKwwrDA8oKwwqDRAnDygQKA4pDikqDSoAARAuDCoNDikpDikODioNKg0qDSoNKikOKQABFCkOKQ4OKigPKQ4NKg0qDSoNKg4pKQ4pAAEUKQ8pDg0qKQ4pDg0qDikOKQ4qDSopDikAARQpDikODSopDikODioNKg0qDSoNKikOKQABFCoNKwwQJykOKg0PKQ4pDygOKRAnKwwrAA0FAAA="
  humidifier_bedroom_plusminus:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_64
        data:
          packet:
            - "JgC2ACkOKg0OKSoOKQ4NKg8oECcpDisMKw0rAAESKwwrDA8oLAssCxAoDygPKCoNKwwpDikAARIrDikODikpDikPDSoNKg0qKQ4pDikOKQABFSkOKQ4NKikOKQ4OKQ4qDSopDikOKQ4pAAEUKQ4pDg4qKA8pDg0qDSoNKikOKQ4pDykAARQpDikODSopDikPDSoNKg0qKQ4qDSoNKgABEysNKg0OKSsMKwwPKBAoDygrDCsMKwwrAA0FAAA="

homeassistant:
  customize:
    script.humidifier_bedroom_onoff:
      icon: mdi:power
      friendly_name: Вкл/Выкл
    script.humidifier_bedroom_night:
      icon: mdi:weather-night
      friendly_name: Ночь
    script.humidifier_bedroom_auto:
      icon: mdi:auto-fix
      friendly_name: Авто
    script.humidifier_bedroom_kids:
      icon: mdi:baby-buggy
      friendly_name: Дети
    script.humidifier_bedroom_heart:
      icon: mdi:heart-pulse
      friendly_name: Сердце
    script.humidifier_bedroom_touch:
      icon: mdi:fingerprint
      friendly_name: Тач
    script.humidifier_bedroom_light:
      icon: mdi:lightbulb-on
      friendly_name: Свет
    script.humidifier_bedroom_time:
      icon: mdi:timer
      friendly_name: Таймер
    script.humidifier_bedroom_heat:
      icon: mdi:radiator
      friendly_name: Нагрев
    script.humidifier_bedroom_uv:
      icon: mdi:weather-sunny
      friendly_name: Ультафиолет
    script.humidifier_bedroom_ion:
      icon: mdi:creation
      friendly_name: Ионизация
    script.humidifier_bedroom_plusminus:
      icon: mdi:plus-minus
      friendly_name: +/-