switch:
  - platform: broadlink
    host: 192.168.1.73
    mac: "34:EA:34:BD:B5:B3"
    type: sp2
    timeout: 15
    friendly_name: salt_lamp

light:
  - platform: mqtt
    name: livingroom
    command_topic: "bridge/rfout/set"
    payload_on: "C001000018007636A4"
    payload_off: "C001000018007636A1"
  - platform: mqtt
    name: livingroom_back
    command_topic: "bridge/rfout/set"
    payload_on: "C001000018007636A8"
    payload_off: "C001000018007636A2"

  - platform: mqtt
    name: bedroom
    command_topic: "bridge/rfout/set"
    payload_on: "C00100001800F94164"
    payload_off: "C00100001800F94161"
  - platform: switch
    name: bedroom_back
    entity_id: switch.salt_lamp

  - platform: mqtt
    name: kitchen
    command_topic: "bridge/rfout/set"
    payload_on: "C0010155180089C868"
    payload_off: "C0010156180089C862"
  - platform: mqtt
    name: kitchen_back
    command_topic: "bridge/rfout/set"
    payload_on: "C0010156180089C864"
    payload_off: "C0010156180089C861"

  - platform: mqtt
    name: wc
    command_topic: "bridge/rfout/set"
    payload_on: "C001015A18000BDAA4"
    payload_off: "C001015A18000BDAA1"
  
  - platform: mqtt
    name: corridor
    command_topic: "bridge/rfout/set"
    payload_on: "C001015F1800304A64"
    payload_off: "C001015F1800304A61"
  
  - platform: mqtt
    name: bathroom
    command_topic: "bridge/rfout/set"
    payload_on: "C001015F1800304A68"
    payload_off: "C001015F1800304A62"
  
  - platform: mqtt
    name: hall
    command_topic: "bridge/rfout/set"
    payload_on: "C00101631800F94168"
    payload_off: "C00101621800F94162"

group:
  light_livingroom:
    icon: mdi:lightbulb
    entities:
      - light.livingroom
      - light.livingroom_back
  light_bedroom:
    icon: mdi:lightbulb
    entities:
      - light.bedroom
      - light.bedroom_back
  light_kitchen:
    icon: mdi:lightbulb
    entities:
      - light.kitchen
      - light.kitchen_back
  light_wc:
    icon: mdi:lightbulb
    entities:
      - light.wc
  light_corridor:
    icon: mdi:lightbulb
    entities:
      - light.corridor
  light_bathroom:
    icon: mdi:lightbulb
    entities:
      - light.bathroom
  light_hall:
    icon: mdi:lightbulb
    entities:
      - light.hall
      - light.hall_back

homeassistant:
  customize:
    light.livingroom:
      friendly_name: Зал
      room: livingroom
    light.livingroom_back:
      friendly_name: Зал ночник
      room: livingroom
    light.bedroom:
      friendly_name: Спальня
      room: bedroom
    light.bedroom_back:
      friendly_name: Спальня ночник
      room: bedroom
    light.kitchen:
      friendly_name: Кухня
      room: kitchen
    light.kitchen_back:
      friendly_name: Кухня ночник
      room: kitchen
    light.wc:
      friendly_name: Туалет
      room: wc
    light.corridor:
      friendly_name: Коридор
      room: corridor
    light.bathroom:
      friendly_name: Ванная
      room: bathroom
    light.hall:
      friendly_name: Прихожая
      room: hall
    light.hall_back:
      friendly_name: Прихожая ночник
      room: hall

    group.light_livingroom:
      friendly_name: Зал
    group.light_bedroom:
      friendly_name: Спальня
    group.light_kitchen:
      friendly_name: Кухня
    group.light_wc:
      friendly_name: Туалет
    group.light_corridor:
      friendly_name: Коридор
    group.light_bathroom:
      friendly_name: Ванная
    group.light_hall:
      friendly_name: Прихожая

