script:
  mamibot_off:
    sequence:
      - service: broadlink.send
        data:
          host: "192.168.1.62"
          packet:
            - "JgCYAGNgEzYTNRMREzUTNhM1ExETNRM2EzUTNRMSEhISEhISEzUTAAJ9Y2ATNRM2ExESNhM1FTQTERI2EzUTNhM2EhETERMSEhISNhMAAoFjYBM1EzYTERI2EzUTNhMREjYTNhI2EzUTERMSEhISEhI2EwACf2JhEzUTNRMSEjYTNRM1ExISNhM1EzUTNhMREhITERMREzYSAA0F"
      - service: broadlink.send
        data:
          host: "192.168.1.64"
          packet:
            - "JgCYAGNgEzYTNRMREzUTNhM1ExETNRM2EzUTNRMSEhISEhISEzUTAAJ9Y2ATNRM2ExESNhM1FTQTERI2EzUTNhM2EhETERMSEhISNhMAAoFjYBM1EzYTERI2EzUTNhMREjYTNhI2EzUTERMSEhISEhI2EwACf2JhEzUTNRMSEjYTNRM1ExISNhM1EzUTNhMREhITERMREzYSAA0F"
  mamibot_on:
    sequence:
      - service: broadlink.send
        data:
          host: "192.168.1.62"
          packet:
            - "JgDmAGJhFjMUNBQQFDQVNBQ0FBETNBU0EzUTNRMRExIRExISEjYSAAKCYmETNRM1ExIUNBM1EzYSEhI2EzUTNhM1ExETERMRExISNhMAAoBjXhU1EzYTERI2EzYTNRMREzUTNhM1EzUVEBISEhISEhM1FQACfmNgEzYTNRMREzUTNhM1ExETNhI2EzUTNhISEhISEhISEzUTAAKAY2ATNhM1ExETNRM2EzUTERM1EzYTNRM1ExISEhISEhITNRMAAjYIQmNgEzUTNhMREjYTNhI2ExESNhM1EzYTNRMRExETEhISEjYTAA0FAAA="
      - service: broadlink.send
        data:
          host: "192.168.1.64"
          packet:
            - "JgDmAGJhFjMUNBQQFDQVNBQ0FBETNBU0EzUTNRMRExIRExISEjYSAAKCYmETNRM1ExIUNBM1EzYSEhI2EzUTNhM1ExETERMRExISNhMAAoBjXhU1EzYTERI2EzYTNRMREzUTNhM1EzUVEBISEhISEhM1FQACfmNgEzYTNRMREzUTNhM1ExETNhI2EzUTNhISEhISEhISEzUTAAKAY2ATNhM1ExETNRM2EzUTERM1EzYTNRM1ExISEhISEhITNRMAAjYIQmNgEzUTNhMREjYTNhI2ExESNhM1EzYTNRMRExETEhISEjYTAA0FAAA="
  mamibot_charge:
    sequence:
      - service: broadlink.send
        data:
          host: "192.168.1.62"
          packet:
            - "JgAMAWJhEzUTNhISEjYTNRM2EhISNhM1EzYTERISEhITERM1EzYTAAJ/Y2ATNRM2ExESNhM1EzYTERI2EzUTNhMRExETERMREzYTNRMAAoBmXRI2EjYSExE3EjgQNxISEjYSNhI3ERMSEhISEhISNhI3EgACgWFiFDQUNBQRFDQUNBQ0FQ8VNBQ0FDQVDxUQFBAWDxUyFTMVggkAAfRiYRUzFjIVEBQ1EzQVMxUQFDQUNBUzFRETEBQRExEUMxU0FAACfmJhFTMWMxQQFDYTMxU0FBETNBQ0FTQUEBQQFBEVDxQ0FDQUAAJ/YmEVMxUzFRAUNBQ0FTMVEBQ0FDQVMxUPFRAUEBQQFDQVMxUADQUAAAAAAAAAAAAAAAA="
      - service: broadlink.send
        data:
          host: "192.168.1.64"
          packet:
            - "JgAMAWJhEzUTNhISEjYTNRM2EhISNhM1EzYTERISEhITERM1EzYTAAJ/Y2ATNRM2ExESNhM1EzYTERI2EzUTNhMRExETERMREzYTNRMAAoBmXRI2EjYSExE3EjgQNxISEjYSNhI3ERMSEhISEhISNhI3EgACgWFiFDQUNBQRFDQUNBQ0FQ8VNBQ0FDQVDxUQFBAWDxUyFTMVggkAAfRiYRUzFjIVEBQ1EzQVMxUQFDQUNBUzFRETEBQRExEUMxU0FAACfmJhFTMWMxQQFDYTMxU0FBETNBQ0FTQUEBQQFBEVDxQ0FDQUAAJ/YmEVMxUzFRAUNBQ0FTMVEBQ0FDQVMxUPFRAUEBQQFDQVMxUADQUAAAAAAAAAAAAAAAA="
  mamibot_clean:
    sequence:
      - service: broadlink.send
        data:
          host: "192.168.1.62"
          packet:
            - "JgDkAGNgEzUTNhMRFDQTNRM2EhISNhM1EzYSEhQ0ExETERM2EhISAAJ8YmEUNBM1ExETNhM1EzUTERM2FDQTNRMREzYTERISEjYTERMAAoBjYBQ0FDUVDxI2FTMVNBUPEjYVMxU0FQ8SNhUPExETNhUPFQACf2JgEzYTNRMREzUTNhM1ExETNRM2EzUTERUzExISEhI2ExETAAJ/Y2AVNBQ0FQ8SNhM2EjYVDxI2EzUTNhUPEjYTERMSEjYTERIAAoFiYRM1EzUTERM2EzUTNRMREzYTNRM1ExETNhMREhITNRMSEgANBQAAAAA="
      - service: broadlink.send
        data:
          host: "192.168.1.64"
          packet:
            - "JgDkAGNgEzUTNhMRFDQTNRM2EhISNhM1EzYSEhQ0ExETERM2EhISAAJ8YmEUNBM1ExETNhM1EzUTERM2FDQTNRMREzYTERISEjYTERMAAoBjYBQ0FDUVDxI2FTMVNBUPEjYVMxU0FQ8SNhUPExETNhUPFQACf2JgEzYTNRMREzUTNhM1ExETNRM2EzUTERUzExISEhI2ExETAAJ/Y2AVNBQ0FQ8SNhM2EjYVDxI2EzUTNhUPEjYTERMSEjYTERIAAoFiYRM1EzUTERM2EzUTNRMREzYTNRM1ExETNhMREhITNRMSEgANBQAAAAA="
  mamibot_clean_border:
    sequence:
      - service: broadlink.send
        data:
          host: "192.168.1.62"
          packet:
            - "JgAKAWNgEzYTNRMREzUVNBQ0FQ8TNRMSEhISEhI2FTMTNhM1ExETAAKAYmETNRM1ExETNhM1EzUTERM2EhISEhISEjYTNRM2EzUTERMAAoBiYRM1EzUTERM2EjYTNRMREzUTEhISEhISNhM1EzYTNRMREwACgGJfFDYTNRMREzYSNhM1ExETNRMSEhISEhI2EzUTNhM1ExETAAKAYmATNhM1ExETNRM2EzUTERM1ExISEhISEjYTNRM1EzYUEBIAAoFiYBU0FTMTERM1EzYUNBMREzUTEhISEhISNhUzFTQTNRMREwACgGJhEzUTNRMSEjYTNRUzExISNhMREhITERM1EzYTNRM1ExISAA0FAAAAAAAAAAAAAAAAAAA="
      - service: broadlink.send
        data:
          host: "192.168.1.64"
          packet:
            - "JgAKAWNgEzYTNRMREzUVNBQ0FQ8TNRMSEhISEhI2FTMTNhM1ExETAAKAYmETNRM1ExETNhM1EzUTERM2EhISEhISEjYTNRM2EzUTERMAAoBiYRM1EzUTERM2EjYTNRMREzUTEhISEhISNhM1EzYTNRMREwACgGJfFDYTNRMREzYSNhM1ExETNRMSEhISEhI2EzUTNhM1ExETAAKAYmATNhM1ExETNRM2EzUTERM1ExISEhISEjYTNRM1EzYUEBIAAoFiYBU0FTMTERM1EzYUNBMREzUTEhISEhISNhUzFTQTNRMREwACgGJhEzUTNRMSEjYTNRUzExISNhMREhITERM1EzYTNRM1ExISAA0FAAAAAAAAAAAAAAAAAAA="

homeassistant:
  customize:
    script.mamibot_off:
      icon: mdi:power-off
      friendly_name: Выкл
    script.mamibot_on:
      icon: mdi:power-on
      friendly_name: Вкл
    script.mamibot_charge:
      icon: mdi:battery-charging-80
      friendly_name: Зарядка
    script.mamibot_clean:
      icon: mdi:border-all
      friendly_name: Очистка
    script.mamibot_clean_border:
      icon: mdi:border-outside
      friendly_name: Очистка краёв