script:
  screen_down:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_62
        data:
          packet:
            - "eACuAAoeHwoeCgofCh4fCR8KHwkLHgoeCx4eCgofCgABOAoeHwoKHh8KHgofCh4KCx4KHh8KHgoKHx4KHwkLHgoeHwofCR8KCh4LHgoeHwoKHgoAATkKHh8JCx4eCh8KHwkfCgoeCx4eCh8KCh4fCh4KCx4KHh8JHwofCgoeCh4LHh8JCx4KAAE4Cx4eCgsdHwofCR8KHwoKHgoeHwofCQseHwkfCgoeCx4eCh8KBAAF3AAAAAAAAAAAAAA="
  screen_up:
    sequence:
      - service: switch.broadlink_send_packet_192_168_1_62
        data:
          packet:
            - "eAC4AB4LHQsJIAkfHgsdCx4LCR8eCwkfCR8KHwkAAToJHx0LCSAdCx4LHQseCwkfCh8dCx4LCR8dDB0LCSAJHx4LHQseCwkfHQwJHwkfCh8JAAE5Ch8dCwkfHgsdDB0LHgsJHwkfHgseCgofHgoeCwkfCh8dCx4LHQsKHx0LCh8JHwofCQABOQoeHgsJIB0LHgoeCx4LCR8JHx4LHgsJHx0LHgsJIAggHQseCx0LCh8dCwofCR8JHwoABdw="

homeassistant:
  customize:
    script.screen_down:
      icon: mdi:download
      friendly_name: Опустить
    script.screen_up:
      icon: mdi:Upload
      friendly_name: Поднять