homeassistant:
  customize:
    # ванная
    sensor.bathroom_temperature:
      friendly_name: Температура
      icon: mdi:thermometer
      device_class: temperature
      room: bathroom
    sensor.bathroom_humidity:
      friendly_name: Влажность
      icon: mdi:water-percent
      device_class: humidity
      room: bathroom
    sensor.bathroom_pressure:
      friendly_name: Давление
      icon: mdi:gauge
      device_class: pressure
      room: bathroom
    binary_sensor.bathroom_waterleak:
      friendly_name: Утечка воды
      device_class: problem
      room: bathroom

    # зал
    binary_sensor.livingroom_window:
      friendly_name: Окно
      device_class: window
      room: livingroom
    binary_sensor.livingroom_balcony:
      friendly_name: Балкон
      device_class: door
      room: livingroom
    binary_sensor.livingroom_motion:
      friendly_name: Движение
      device_class: occupancy
      room: livingroom
    sensor.livingroom_illuminance:
      friendly_name: Яркость
      device_class: illuminance
      room: livingroom
    sensor.livingroom_cube:
      friendly_name: Действие
      device_class: touch
      icon: mdi:gesture-double-tap
      room: livingroom

    # кухня
    binary_sensor.kitchen_motion:
      friendly_name: Движение
      device_class: occupancy
      room: kitchen
    sensor.kitchen_illuminance:
      friendly_name: Яркость
      device_class: illuminance
      room: kitchen
    binary_sensor.kitchen_waterleak:
      friendly_name: Утечка воды
      device_class: problem
      room: kitchen
    binary_sensor.kitchen_window:
      friendly_name: Окно
      device_class: window
      room: kitchen

    # прихожая
    binary_sensor.hall_motion:
      friendly_name: Движение
      device_class: motion
      room: hall
    sensor.hall_illuminance:
      friendly_name: Яркость
      device_class: illuminance
      room: hall
    sensor.hall_illuminance_gw:
      friendly_name: Яркость
      device_class: illuminance
      room: other
    binary_sensor.hall_entrance:
      friendly_name: Вход
      device_class: door
      room: hall

    sensor.hall_temperature:
      friendly_name: Температура
      icon: mdi:thermometer
      device_class: temperature
      room: hall
    sensor.hall_humidity:
      friendly_name: Влажность
      icon: mdi:water-percent
      device_class: humidity
      room: hall
    sensor.hall_pressure:
      friendly_name: Давление
      icon: mdi:gauge
      device_class: pressure
      room: hall

    # спальня
    binary_sensor.bedroom_motion:
      friendly_name: Движение
      device_class: motion
      room: bedroom
    sensor.bedroom_illuminance:
      friendly_name: Яркость
      device_class: illuminance
      room: bedroom
    binary_sensor.bedroom_window:
      friendly_name: Окно
      device_class: window
      room: bedroom

    # туалет
    binary_sensor.wc_waterleak:
      friendly_name: Утечка воды
      device_class: problem
      room: wc

    # балкон
    sensor.balcony_temperature:
      friendly_name: Температура
      icon: mdi:thermometer
      device_class: temperature
      room: other
    sensor.balcony_humidity:
      friendly_name: Влажность
      icon: mdi:water-percent
      device_class: humidity
      room: other
    sensor.balcony_pressure:
      friendly_name: Давление
      icon: mdi:gauge
      device_class: pressure
      room: other
