sensor:
  - platform: template
    sensors:
      flat_temperature_count:
        entity_id:
          - sensor.livingroom_temperature
          - sensor.bedroom_temperature
          - sensor.kitchen_temperature
          - sensor.bathroom_temperature
          - sensor.hall_temperature
        value_template: >- 
          {{ states.sensor |
             rejectattr('state','eq','unavailable') | 
             rejectattr('state','eq','unknown') |
             rejectattr('attributes.room', 'eq', 'other') |
             selectattr('attributes.device_class', 'eq', 'temperature') |
             list | count | int }}
      flat_temperature_sum:
        entity_id:
          - sensor.livingroom_temperature
          - sensor.bedroom_temperature
          - sensor.kitchen_temperature
          - sensor.bathroom_temperature
          - sensor.hall_temperature
        value_template: >- 
          {{ (states.sensor |
              rejectattr('state','eq','unavailable') | 
              rejectattr('state','eq','unknown') |
              rejectattr('attributes.room', 'eq', 'other') |
              selectattr('attributes.device_class', 'eq', 'temperature') |
              map(attribute='state') | map('float') | sum) | round(2) }}
      flat_temperature:
        unit_of_measurement: "°C"
        entity_id:
          - sensor.flat_temperature_count
          - sensor.flat_temperature_sum
        value_template: >- 
          {{ ((states.sensor.flat_temperature_sum.state | float) / (states.sensor.flat_temperature_count.state | float)) | round(2) }}

      flat_humidity_count:
        entity_id:
          - sensor.livingroom_humidity
          - sensor.bedroom_humidity
          - sensor.kitchen_humidity
          - sensor.bathroom_humidity
          - sensor.hall_humidity
        value_template: >- 
          {{ states.sensor |
             rejectattr('state','eq','unavailable') |
             rejectattr('state','eq','unknown') |
             rejectattr('attributes.room', 'eq', 'other') |
             selectattr('attributes.device_class', 'eq', 'humidity') |
             list | count | int }}
      flat_humidity_sum:
        entity_id:
          - sensor.livingroom_humidity
          - sensor.bedroom_humidity
          - sensor.kitchen_humidity
          - sensor.bathroom_humidity
          - sensor.hall_humidity
        value_template: >- 
          {{ (states.sensor |
              rejectattr('state','eq','unavailable') |
              rejectattr('state','eq','unknown') |
             rejectattr('attributes.room', 'eq', 'other') |
              selectattr('attributes.device_class', 'eq', 'humidity') |
              map(attribute='state') | map('float') | sum) | round(2) }}
      flat_humidity:
        unit_of_measurement: "%"
        entity_id:
          - sensor.flat_humidity_count
          - sensor.flat_humidity_sum
        value_template: >- 
          {{ ((states.sensor.flat_humidity_sum.state | float) / (states.sensor.flat_humidity_count.state | float)) | round(2) }}

      flat_pressure_count:
        entity_id:
          - sensor.bathroom_pressure
          - sensor.hall_pressure
        value_template: >- 
          {{ states.sensor |
             rejectattr('state','eq','unavailable') |
             rejectattr('state','eq','unknown') |
             rejectattr('attributes.room', 'eq', 'other') |
             selectattr('attributes.device_class', 'eq', 'pressure') |
             list | count | int }}
      flat_pressure_sum:
        entity_id:
          - sensor.bathroom_pressure
          - sensor.hall_pressure
        value_template: >- 
          {{ (states.sensor |
              rejectattr('state','eq','unavailable') |
              rejectattr('state','eq','unknown') |
             rejectattr('attributes.room', 'eq', 'other') |
              selectattr('attributes.device_class', 'eq', 'pressure') |
              map(attribute='state') | map('float') | sum) | round(2) }}
      flat_pressure:
        unit_of_measurement: hPa
        entity_id:
          - sensor.flat_pressure_count
          - sensor.flat_pressure_sum
        value_template: >- 
          {{ ((states.sensor.flat_pressure_sum.state | float) / (states.sensor.flat_pressure_count.state | float)) | round(2) }}

homeassistant:
  customize:
    # общее
    sensor.flat_temperature:
      friendly_name: Температура
      icon: mdi:thermometer
      device_class: temperature
      room: other
    sensor.flat_humidity:
      friendly_name: Влажность
      icon: mdi:water-percent
      device_class: humidity
      room: other
    sensor.flat_pressure:
      friendly_name: Давление
      icon: mdi:gauge
      device_class: pressure
      room: other