sensor:
  - platform: darksky
    api_key: !secret darksky_key
    monitored_conditions:
      - temperature
      - humidity
      - pressure
      - cloud_cover
      - precip_type
      - precip_probability
      - precip_intensity
      - wind_speed
      - wind_bearing
    scan_interval:
      minutes: 20

homeassistant:
  customize:
    # на улице
    sensor.dark_sky_temperature:
      friendly_name: Температура
      icon: mdi:thermometer
      device_class: temperature
      room: outdoor
    sensor.dark_sky_humidity:
      friendly_name: Влажность
      icon: mdi:water-percent
      device_class: humidity
      room: outdoor
    sensor.dark_sky_pressure:
      friendly_name: Давление
      icon: mdi:gauge
      device_class: pressure
      room: outdoor
