sensor:
  - platform: template
    sensors:
      hall_temperature:
        unit_of_measurement: "°C"
        entity_id: sensor.flat_temperature
        value_template: "{{ states.sensor.flat_temperature.state }}"
      hall_humidity:
        unit_of_measurement: "%"
        entity_id: sensor.flat_humidity
        value_template: "{{ states.sensor.flat_humidity.state }}"
      hall_battery:
        unit_of_measurement: "%"
        entity_id: sensor.flat_humidity
        value_template: "{{ 0 }}"
      balcony_temperature:
        unit_of_measurement: "°C"
        entity_id: sensor.flat_temperature
        value_template: "{{ states.sensor.flat_temperature.state }}"
      balcony_humidity:
        unit_of_measurement: "%"
        entity_id: sensor.flat_humidity
        value_template: "{{ states.sensor.flat_humidity.state }}"
      balcony_battery:
        unit_of_measurement: "%"
        entity_id: sensor.flat_humidity
        value_template: "{{ 0 }}"

homeassistant:
  customize:
    # прихожая
    sensor.hall_temperature:
      friendly_name: Температура
      icon: mdi:thermometer
      device_class: temperature
      room: hall
    sensor.hall_humidity:
      friendly_name: Влажность
      icon: mdi:water-percent
      device_class: humidity
      room: hall
    sensor.hall_temperature_battery:
      friendly_name: Батарея
      device_class: battery
      room: hall


    # балкон
    sensor.balcony_temperature:
      friendly_name: Температура
      icon: mdi:thermometer
      device_class: temperature
      room: other
    sensor.balcony_humidity:
      friendly_name: Влажность
      icon: mdi:water-percent
      device_class: humidity
      room: other
    sensor.balcony_temperature_battery:
      friendly_name: Батарея
      device_class: battery
      room: other
