script:
  open_projector_screen:
    sequence:
      - service: broadlink.send
        data:
          host: "192.168.1.62"
          packet:
            - "eAC4AB4LHQsJIAkfHgsdCx4LCR8eCwkfCR8KHwkAAToJHx0LCSAdCx4LHQseCwkfCh8dCx4LCR8dDB0LCSAJHx4LHQseCwkfHQwJHwkfCh8JAAE5Ch8dCwkfHgsdDB0LHgsJHwkfHgseCgofHgoeCwkfCh8dCx4LHQsKHx0LCh8JHwofCQABOQoeHgsJIB0LHgoeCx4LCR8JHx4LHgsJHx0LHgsJIAggHQseCx0LCh8dCwofCR8JHwoABdw="
  close_projector_screen:
    sequence:
      - service: broadlink.send
        data:
          host: "192.168.1.62"
          packet:
            - "eACuAAoeHwoeCgofCh4fCR8KHwkLHgoeCx4eCgofCgABOAoeHwoKHh8KHgofCh4KCx4KHh8KHgoKHx4KHwkLHgoeHwofCR8KCh4LHgoeHwoKHgoAATkKHh8JCx4eCh8KHwkfCgoeCx4eCh8KCh4fCh4KCx4KHh8JHwofCgoeCh4LHh8JCx4KAAE4Cx4eCgsdHwofCR8KHwoKHgoeHwofCQseHwkfCgoeCx4eCh8KBAAF3AAAAAAAAAAAAAA="
  stop_projector_screen:
    sequence:
      - service: broadlink.send
        data:
          host: "192.168.1.62"
          packet:
            - "eAC4AB4LHQsJIAkfHgsdCx4LCR8eCwkfCR8KHwkAAToJHx0LCSAdCx4LHQseCwkfCh8dCx4LCR8dDB0LCSAJHx4LHQseCwkfHQwJHwkfCh8JAAE5Ch8dCwkfHgsdDB0LHgsJHwkfHgseCgofHgoeCwkfCh8dCx4LHQsKHx0LCh8JHwofCQABOQoeHgsJIB0LHgoeCx4LCR8JHx4LHgsJHx0LHgsJIAggHQseCx0LCh8dCwofCR8JHwoABdw="

cover:
  - platform: template
    covers:
      projector_screen:
        open_cover:
          service: script.open_projector_screen
        close_cover:
          service: script.close_projector_screen
        stop_cover:
          service: script.stop_projector_screen
  - platform: mqtt
    name: shutters_kitchen
    command_topic: "bridge/rfout/set"
    payload_open: "C001016E18000B60E8"
    payload_close: "C001016D18000B60E2"
    payload_stop: "C001016D18000B60E4"

homeassistant:
  customize:
    cover.projector_screen:
      friendly_name: Экран проектора
      room: livingroom

    cover.shutters_kitchen:
      friendly_name: Рольставни Кухня
      room: kitchen

