- alias: mqtt_sensor_redirect
  trigger:
    - platform: mqtt
      topic: bridge/rfin
  action:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfin_sensor
        payload_template: "{{trigger.payload[9:]}}"
