# security alarm
- alias: Security ARM_AWAY
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005444C0"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA8"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005D7DC0"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: ARM_AWAY

- alias: Security ARM_HOME
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "800544403"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA1"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005D7D03"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: ARM_HOME

- alias: Security DISARM
  trigger:
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "80054440C"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8000CFBA4"
    - platform: mqtt
      topic: bridge/rfin_sensor
      payload: "8005D7D0C"
  action:
    - service: mqtt.publish
      data_template:
        topic: home/alarm/set
        payload: DISARM

# - alias: Security PANIC
#   trigger:
#     - platform: mqtt
#       topic: bridge/rfin_sensor
#       payload: "800544430"
#   trigger:
#     - platform: mqtt
#       topic: bridge/rfin_sensor
#       payload: "8000CFBA2"
#     - platform: mqtt
#       topic: bridge/rfin_sensor
#       payload: "8005D7D30"
#   action:
#     - service: mqtt.publish
#       data_template:
#         topic: home/alarm
#         payload_template: triggered

- alias:  Security ARM_AWAY to External
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: armed_away
  action:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfout/set
        payload: C001016C18000CEBA8
- alias:  Security ARM_HOME to External
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: armed_home
  action:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfout/set
        payload: C001016C18000CEBA2
- alias:  Security DISARM to External
  trigger:
    platform: state
    entity_id: alarm_control_panel.ha_alarm
    to: disarmed
  action:
    - service: mqtt.publish
      data_template:
        topic: bridge/rfout/set
        payload: C001016C18000CEBA4
# - alias:  Security PANIC to External
#   trigger:
#     platform: state
#     entity_id: alarm_control_panel.ha_alarm
#     to: disarmed
#   action:
#     - service: mqtt.publish
#       data_template:
#         topic: bridge/rfout/set
#         payload: C001016B18000CEBA1
