- alias: Oksana Came Home
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     to: home
  action:
    service: notify.telegram
    data_template:
      message: "Оксана вернулась домой"

- alias: Andrew Came Home
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_drronnie
     to: home
  action:
    service: notify.telegram
    data_template:
      message: "Андрей вернулся домой"

- alias: Oksana Left Home
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_oksana
     to: not_home
  action:
    service: notify.telegram
    data_template:
      message: "Оксана ушла из дома"

- alias: Andrew Left Home
  trigger:
   - platform: state
     entity_id:
       - device_tracker.phone_drronnie
     to: not_home
  action:
    service: notify.telegram
    data_template:
      message: "Андрей ушел из дома"